// Zhixin Paper — Site Data
// Design: Modern Professional Blue

export const COMPANY = {
  name: "Zhixin Paper",
  tagline: "One-Stop Thermal Consumables Platform",
  description:
    "Leading manufacturer of thermal paper rolls and thermal labels, supplying distributors, importers, and factories across Europe, USA, and Canada.",
  email: "Sales@zxpapers.com",
  phone: "+86 153 3924 7872",
  whatsapp: "+86 187 9277 1927",
  address: "Building 15, Phase 1 Zone 2, Ronghao Industrial Park, Gaoling District, Xi'an, Shaanxi, China",
  founded: "2008",
  certifications: ["Quality system documents", "Phenol test reports", "Material declarations", "Chain-of-custody options", "Application-specific document review"],
  stats: [
    { value: "By RFQ", label: "Capacity & Production Plan" },
    { value: "By Route", label: "Markets & Delivery Coverage" },
    { value: "Since 2008", label: "Operating History" },
    { value: "By Scope", label: "Available Documents" },
  ],
};

export const THERMAL_PAPER_ROLLS = [
  {
    slug: "standard-pos-rolls",
    name: "Standard POS Rolls",
    subtitle: "Cash Register & Receipt Paper",
    heroDesc: "Standard receipt rolls configured by printer model, width, outside diameter, core, winding direction, paper grade, and packing plan.",
    description: "POS thermal paper for retail, supermarket, restaurant, and distributor programs. Buyers can select BPA-free, BPS-free, or phenol-free grades according to the destination requirement and available documentation. Printer fit is confirmed against the exact model, dimensions, and approved sample rather than a brand name alone. Plain, back-printed, OEM, and private-label packing options are available subject to artwork, material, and order review.",
    keywords: "POS thermal paper rolls, cash register rolls, receipt paper wholesale, Epson compatible POS paper, 80x80mm thermal rolls, 57x40mm receipt rolls",
    sizes: ["57×38mm", "57×40mm", "57×50mm", "80×40mm", "80×50mm", "80×60mm", "80×80mm"],
    applications: ["Retail POS", "Supermarkets", "Restaurants"],
    features: [
      "Thermal sensitivity selected for the printer speed and image-density target",
      "BPA-free, BPS-free, or phenol-free routes by selected grade",
      "Model-based width, OD, core, and winding verification before bulk approval",
      "Roll diameter and packing tolerances controlled by the approved SKU",
    ],
    moq: "Confirmed by specification, print, packing, and quantity",
    specifications: {
      "Grammage (GSM)": "48g / 55g / 60g",
      "Thickness": "60μm – 75μm",
      "Brightness": "≥ 92%",
      "Image Life": "Selected by grade and validated for the storage condition",
      "Core Options": "Plastic / Cardboard (12mm, 17mm, 25mm)",
      "Phenol Options": "BPA-free / BPS-free / Phenol-free, subject to grade",
      "Print Speed": "Confirmed with printer and selected paper sensitivity",
      "Min. Order Qty": "Confirmed by specification, print, packing, and quantity",
      "Lead Time": "Confirmed after specification, artwork, sample, and capacity review",
      "Documents": "Available documents reviewed by quoted product, site, scope, and validity",
    },
    priority: "P1",
  },
  {
    slug: "credit-card-terminal-rolls",
    name: "Credit Card Terminal Rolls",
    subtitle: "Payment Terminal & EDC Receipt Paper",
    heroDesc: "Compact direct thermal receipt rolls qualified by terminal model, width, OD or length, core ID, winding direction, paper grade, and pack plan.",
    description: "Credit card terminal paper rolls for payment-terminal distributors, merchant service providers, banks, acquiring channels, and multi-model device fleets. Common buyer names include payment terminal rolls, EDC rolls, EFTPOS rolls, and credit card machine paper. Compatibility is confirmed against the exact terminal and approved sample rather than brand name alone.",
    keywords: "credit card terminal paper rolls, payment terminal rolls, credit card machine paper, EDC paper rolls, EFTPOS rolls, 57mm thermal paper rolls, 2 1/4 inch receipt paper",
    sizes: ["57×38mm", "57×40mm", "57×50mm", "2 1/4 in × 50 ft", "2 1/4 in × 85 ft", "Custom by model"],
    applications: ["Countertop payment terminals", "Mobile POS terminals", "EDC machines", "EFTPOS fleets"],
    features: [
      "Model-based fit check before bulk approval",
      "Width, OD or length, core, and winding locked by SKU",
      "BPA-free, BPS-free, or phenol-free routes by selected grade",
      "Plain, reverse-print, and private-label packing options",
    ],
    moq: "Confirmed by size, packing, and annual volume",
    specifications: {
      "Common Width Family": "57mm / 2 1/4 inch",
      "Length or OD": "Confirmed by terminal compartment and buyer format",
      "Core Options": "Coreless or specified core ID, subject to model",
      "Winding Direction": "Confirmed from current roll or terminal path",
      "Paper Grade": "Matched by sensitivity, image-life, and document need",
      "End Mark / Black Mark": "Available when required by the mechanism",
      "Printing": "Plain or controlled reverse-side print",
      "Packing": "Units per box, carton count, and SKU marks confirmed at RFQ",
    },
    tag: "SEO",
  },
  {
    slug: "atm-banking-rolls",
    name: "ATM & Bank Receipt Rolls",
    subtitle: "ATM, Teller & Financial Terminal Paper",
    heroDesc: "ATM and banking receipt rolls configured by terminal model, paper path, retention target, anti-static requirement, and approved disclosure copy.",
    description: "Thermal receipt stock for ATMs, teller terminals, financial kiosks, and currency-service equipment. The project specification should define the exact terminal, width, roll diameter, core, paper sensitivity, retention requirement, storage condition, phenol requirement, and back-print content. Anti-static treatment, archival-grade options, and controlled reverse printing are selected subject to material and project review. Production-intent samples allow the buyer to verify feed, cut, print density, static behavior, and image stability before bulk approval.",
    keywords: "ATM paper rolls, bank receipt paper, ATM thermal paper wholesale, banking receipt rolls, archival grade thermal paper, Diebold Nixdorf paper, NCR ATM paper, phenol option bank receipt paper, back print thermal paper",
    sizes: ["57×40mm", "57×50mm", "80×60mm", "80×70mm", "80×80mm", "82.5×80mm", "Custom"],
    applications: ["ATM machines", "Bank teller terminals", "Financial kiosks", "Currency exchange terminals", "Investment trading terminals"],
    features: [
      "Image-retention grade selected for the buyer's record and storage requirement",
      "Anti-static treatment available when required by the terminal mechanism",
      "Paper sensitivity verified against the named terminal and print-speed target",
      "BPA-free, BPS-free, or phenol-free routes by selected grade",
      "Model-based fit check for Diebold Nixdorf, NCR, Wincor, Hyosung, and other terminals",
      "Controlled back-print option for approved disclosures, terms, or messaging",
    ],
    moq: "Confirmed by specification, print, packing, and quantity",
    specifications: {
      "Grammage (GSM)": "55g / 65g / 70g",
      "Thickness": "70μm – 85μm",
      "Brightness": "≥ 92%",
      "Image Life": "Grade selected for the required retention and storage condition",
      "Anti-Static Coating": "Available subject to terminal requirement",
      "Back-Print Option": "Available from approved artwork",
      "Core Options": "Plastic (17mm, 25mm)",
      "Phenol Options": "BPA-free / BPS-free / Phenol-free, subject to grade",
      "Print Speed": "Validated with the named terminal and paper sensitivity",
      "Terminal Fit": "Confirmed by model dimensions and approved sample",
      "Min. Order Qty": "Confirmed by specification, print, packing, and quantity",
      "Lead Time": "Confirmed after specification, artwork, sample, and capacity review",
      "Documents": "Available documents reviewed by quoted product, destination, scope, and validity",
    },
    priority: "P1",
  },
  {
    slug: "lottery-gaming-rolls",
    name: "Lottery & Gaming Rolls",
    subtitle: "Lottery Ticket Thermal Paper",
    heroDesc: "Lottery and gaming ticket stock configured around terminal fit, sensing layout, barcode requirement, retention target, and security-print options.",
    description: "Thermal ticket rolls for lottery terminals, gaming machines, and betting-shop printers. Buyers should specify the terminal model, width, core, winding, black-mark or gap-sensing layout, barcode grade, ticket-validity period, and storage conditions. Optional security features can include UV-reactive ink, void patterns, controlled numbering, or custom back printing, subject to process and artwork review. Samples support feed, sensor, cut, barcode, and image-stability validation before production.",
    keywords: "lottery ticket thermal paper, gaming ticket paper supplier, lottery terminal paper rolls, gaming paper wholesale",
    sizes: ["57×40mm", "80×50mm", "80×80mm", "80×70mm", "Custom widths"],
    applications: ["Lottery terminals", "Gaming machines", "Betting shops"],
    features: [
      "Thermal coating selected for the barcode density and scanner requirement",
      "Image-retention grade matched to ticket validity and storage conditions",
      "Optional UV-reactive ink, void patterns, and controlled numbering",
      "Terminal compatibility confirmed by model and approved sample",
    ],
    moq: "Confirmed by specification, print, packing, and quantity",
    specifications: {
      "Grammage (GSM)": "55g / 60g",
      "Thickness": "65μm – 80μm",
      "Coating Density": "High-density (barcode optimised)",
      "Image Life": "Selected for ticket validity and storage conditions",
      "Security Features": "UV-reactive ink, Void patterns (optional)",
      "Core Options": "Plastic / Cardboard (17mm, 25mm)",
      "Print Speed": "Validated with the named mechanism, settings, and selected grade",
      "Min. Order Qty": "Confirmed by specification, print, packing, and quantity",
      "Lead Time": "Confirmed after specification, artwork, sample, and capacity review",
      "Documents": "Available documents reviewed by quoted product, site, scope, and validity",
    },
    tag: "SEO",
  },
  {
    slug: "casino-tito-rolls",
    name: "Casino TITO Rolls",
    subtitle: "Ticket-In Ticket-Out Paper",
    heroDesc: "TITO ticket stock configured by slot platform, ticket geometry, barcode requirement, environmental exposure, and packing plan.",
    description: "Ticket-In Ticket-Out stock for casino slot machines, terminals, and gaming kiosks. The approved specification should define the platform model, ticket dimensions, sensing layout, barcode grade, thermal sensitivity, retention target, humidity exposure, and carton identification. Moisture-protective packing and higher-retention grades are available subject to project review. Production-intent samples support feed, cut, sensor, print-density, and scanner validation before bulk production.",
    keywords: "casino TITO paper, slot machine receipt paper, ticket-in ticket-out paper, IGT compatible TITO rolls, casino thermal paper wholesale",
    sizes: ["80×70mm", "80×80mm"],
    applications: ["Slot machines", "Casino terminals", "Gaming kiosks"],
    features: [
      "Coating selected for the barcode density and scanner requirement",
      "Print speed validated against the named mechanism and paper grade",
      "Moisture-protective packaging available for the storage plan",
      "IGT, Aristocrat, Konami, and other platform fit confirmed by model and sample",
    ],
    moq: "Confirmed by specification, print, packing, and quantity",
    specifications: {
      "Grammage (GSM)": "55g / 60g",
      "Thickness": "65μm – 80μm",
      "Coating": "High-density barcode optimised",
      "Image Life": "Selected for retention and storage conditions",
      "Humidity Protection": "Protective packaging available by storage plan",
      "Core Options": "Plastic (17mm, 25mm)",
      "Print Speed": "Validated with the named mechanism and paper grade",
      "Min. Order Qty": "Confirmed by specification, print, packing, and quantity",
      "Lead Time": "Confirmed after specification, artwork, sample, and capacity review",
      "Documents": "Available documents reviewed by quoted product, site, scope, and validity",
    },
    tag: "SEO",
  },
  {
    slug: "parking-ticketing-rolls",
    name: "Parking & Ticketing Rolls",
    subtitle: "Parking Ticket Paper",
    heroDesc: "Parking and ticketing rolls configured by machine, sensing method, dimensions, barcode target, exposure conditions, and retention requirement.",
    description: "Thermal ticket stock for parking meters, toll booths, and transit equipment. Outdoor performance depends on the selected coating, printer, UV and moisture exposure, temperature range, ticket handling, and retention target. Buyers should provide the machine model, dimensions, black-mark or gap layout, barcode requirement, and operating environment. Production-intent samples support feed, cut, sensor, scanner, and exposure checks before bulk approval.",
    keywords: "parking ticket paper, thermal ticket rolls",
    sizes: ["57×38mm", "57×40mm", "80×50mm", "80×60mm", "Custom"],
    applications: ["Parking meters", "Toll booths", "Transit ticketing"],
    features: [
      "UV-resistant coating options selected for the exposure target",
      "Moisture-resistant grades available for the operating environment",
      "Barcode readability validated with the named printer and scanner",
      "Custom dimensions subject to machine, die, and sample review",
    ],
    moq: "Confirmed by specification, print, packing, and quantity",
    specifications: {
      "Grammage (GSM)": "55g / 60g",
      "Thickness": "65μm – 80μm",
      "UV Resistance": "Validated for the selected grade and exposure target",
      "Weather Resistance": "Validated for the selected grade and moisture exposure",
      "Image Life": "Selected for the outdoor retention target and validated under intended exposure",
      "Core Options": "Plastic / Cardboard (17mm, 25mm)",
      "Print Speed": "Validated with the named mechanism, settings, and selected grade",
      "Min. Order Qty": "Confirmed by specification, print, packing, and quantity",
      "Lead Time": "Confirmed after specification, artwork, sample, and capacity review",
      "Documents": "Available documents reviewed by quoted product, site, scope, and validity",
    },
    tag: "SEO",
  },
  {
    slug: "medical-rolls",
    name: "Medical Paper Rolls",
    subtitle: "Patient Records & Medical Receipts",
    heroDesc: "Medical receipt and record rolls selected by device, retention target, chemical exposure, storage condition, and required material documentation.",
    description: "Thermal paper for hospital kiosks, pharmacy POS systems, and compatible medical-device outputs. Buyers should identify the device model, dimensions, paper path, retention period, storage environment, cleaning chemicals, phenol requirement, and applicable documentation. BPA-free and longer-retention grades are available subject to material selection. Samples allow print, feed, chemical-exposure, and image-stability checks in the actual workflow before production approval.",
    keywords: "medical thermal paper, patient receipt paper, phenol option medical paper, medical material document review, hospital receipt rolls",
    sizes: ["57×38mm", "57×40mm", "57×50mm", "80×50mm", "80×80mm"],
    applications: ["Hospital kiosks", "Pharmacy POS", "Medical devices"],
    features: [
      "BPA-free, BPS-free, or phenol-free routes by selected grade",
      "Image-retention grade selected for the record and storage requirement",
      "Chemical resistance validated against the buyer's named cleaning agents",
      "Material documents supplied according to the selected grade and destination review",
    ],
    moq: "Confirmed by specification, print, packing, and quantity",
    specifications: {
      "Grammage (GSM)": "55g / 60g",
      "Thickness": "65μm – 80μm",
      "Phenol Options": "BPA-free / BPS-free / Phenol-free, subject to grade",
      "Image Life": "Selected for the required retention and storage condition",
      "Chemical Resistance": "Validated against the named cleaning agents",
      "Core Options": "Plastic / Cardboard (12mm, 17mm, 25mm)",
      "Print Speed": "Validated with the named mechanism, settings, and selected grade",
      "Min. Order Qty": "Confirmed by specification, print, packing, and quantity",
      "Lead Time": "Confirmed after specification, artwork, sample, and capacity review",
      "Documents": "Available documents reviewed by quoted construction, intended use, and scope",
    },
  },
  {
    slug: "transport-ticket-rolls",
    name: "Transport Ticket Rolls",
    subtitle: "Bus, Rail & Transit Tickets",
    heroDesc: "Transport ticket stock configured by printer, sensing layout, barcode target, handling profile, retention requirement, and security-print options.",
    description: "Thermal ticket stock for bus, rail, ferry, and public-transport workflows. The approved specification should identify the ticket printer, dimensions, sensing layout, barcode or magnetic requirement, handling, light exposure, retention target, and security-print options. Fit for Scheidt & Bachmann, Parkeon, Cubic, and other systems is confirmed by the exact mechanism and sample rather than brand name alone. Custom dimensions and security features are subject to engineering and artwork review.",
    keywords: "bus ticket paper, rail ticket paper rolls",
    sizes: ["57×38mm", "57×40mm", "80×50mm", "80×60mm", "Custom"],
    applications: ["Bus terminals", "Train stations", "Ferry terminals"],
    features: [
      "Barcode durability validated against the specified handling test and scanner target",
      "Print throughput qualified with the named mechanism, settings, and paper grade",
      "Fit checked against the exact Scheidt & Bachmann, Parkeon, Cubic, or other mechanism and sample",
      "Custom security features available for anti-fraud applications",
    ],
    moq: "Confirmed by specification, print, packing, and quantity",
    specifications: {
      "Grammage (GSM)": "55g / 60g",
      "Thickness": "65μm – 80μm",
      "Coating": "Durable, high-contrast",
      "Image Life": "Selected for the retention target and validated under intended conditions",
      "Core Options": "Plastic / Cardboard (17mm, 25mm)",
      "Print Speed": "Validated with the named mechanism, settings, and selected grade",
      "Min. Order Qty": "Confirmed by specification, print, packing, and quantity",
      "Lead Time": "Confirmed after specification, artwork, sample, and capacity review",
      "Documents": "Available documents reviewed by quoted product, site, scope, and validity",
    },
    tag: "New",
  },
  {
    slug: "kiosk-vending-rolls",
    name: "Kiosk & Vending Rolls",
    subtitle: "Kiosk Receipt & Vending Machine Paper",
    heroDesc: "Kiosk and vending rolls configured by machine, compartment, operating profile, paper path, environmental exposure, and service plan.",
    description: "Thermal rolls for unattended kiosks and vending machines. Material selection depends on the exact mechanism, compartment dimensions, paper path, temperature and humidity profile, exposure duration, print settings, and maintenance cycle. Core size, roll diameter, sensitivity, and packing should be verified with production-intent samples under the buyer's operating conditions before bulk approval.",
    keywords: "kiosk receipt paper, vending machine rolls",
    sizes: ["57×38mm", "57×40mm", "57×50mm", "80×50mm", "80×80mm"],
    applications: ["Self-service kiosks", "Vending machines", "Information terminals"],
    features: [
      "Operating range confirmed by paper grade, mechanism, exposure duration, and acceptance test",
      "Feed behavior validated in the named unattended machine and paper path",
      "Core and roll dimensions matched to the exact printer compartment",
      "Roll length selected against compartment limits and the buyer's service plan",
    ],
    moq: "Confirmed by specification, print, packing, and quantity",
    specifications: {
      "Grammage (GSM)": "48g / 55g / 60g",
      "Thickness": "60μm – 75μm",
      "Operating Temp.": "Confirmed by grade, mechanism, exposure duration, and acceptance test",
      "Image Life": "Selected for the retention target and validated under intended conditions",
      "Core Options": "Plastic / Cardboard (12mm, 17mm, 25mm)",
      "Print Speed": "Validated with the named mechanism, settings, and selected grade",
      "Min. Order Qty": "Confirmed by specification, print, packing, and quantity",
      "Lead Time": "Confirmed after specification, artwork, sample, and capacity review",
      "Documents": "Available documents reviewed by quoted product, site, scope, and validity",
    },
    tag: "New",
  },
  {
    slug: "custom-printed-rolls",
    name: "Custom Printed Rolls",
    subtitle: "OEM & Private Label Thermal Paper",
    heroDesc: "Custom printed receipt rolls configured by artwork, print side, colors, paper grade, printer fit, packing, and destination-document requirements.",
    description: "Front- and back-printed thermal rolls for branding, approved disclosures, coupons, QR codes, loyalty messaging, and private-label programs. The project is specified from the roll dimensions, printer, paper grade, artwork, print colors, registration tolerance, QR or barcode size, and packing plan. BPA-free, phenol-free, and material-document options depend on the selected grade and destination review. Artwork proofs and production-intent samples are approved before bulk printing; campaign performance depends on the offer, audience, placement, and redemption workflow.",
    keywords: "custom printed thermal rolls, OEM thermal paper, private label receipt paper, branded thermal rolls, custom logo receipt paper, back print thermal paper, receipt paper with logo, promotional receipt paper, QR code receipt paper, custom thermal paper wholesale",
    sizes: ["57×38mm", "57×40mm", "57×50mm", "80×40mm", "80×50mm", "80×60mm", "80×80mm", "Custom widths"],
    applications: ["Brand promotion on receipts", "Promotional coupons & loyalty programs", "QR code marketing", "Private label & OEM", "ATM back-print disclosures"],
    features: [
      "Front-print: logo, address, website URL on every receipt header",
      "Back-print options for approved coupons, QR codes, loyalty details, or disclosures",
      "Pantone spot-color matching available subject to proof approval",
      "Paper grade and material documents confirmed for each custom order",
      "Artwork accepted as AI, EPS, or PDF; print template available",
      "Production-intent sample available subject to specification, tooling, quantity, and quote approval",
    ],
    moq: "Confirmed by specification, print, packing, and quantity",
    specifications: {
      "Grammage (GSM)": "48g / 55g / 60g / 65g",
      "Print Method": "Flexographic (water-based inks)",
      "Print Side": "Front-side / Back-side / Both",
      "Colors": "1-4 colors (CMYK); Pantone spot color available",
      "Artwork Format": "AI / EPS / PDF (vector)",
      "QR Code Size": "Confirmed by artwork, DPI, contrast, substrate, and scanner test",
      "Packaging": "Custom branded packaging available",
      "BPA Status": "BPA-free route available by selected grade and current document review",
      "Core Options": "Plastic / Cardboard (12mm, 17mm, 25mm)",
      "Min. Order Qty": "Confirmed by specification, print, packing, and quantity",
      "Lead Time": "Confirmed after specification, artwork, sample, and capacity review",
      "Documents": "Available documents reviewed by quoted product, destination, scope, and validity",
    },
  },
  {
    slug: "back-print-thermal-rolls",
    name: "Back Print Thermal Rolls",
    subtitle: "Pre-Printed Reverse Side Thermal Paper",
    heroDesc: "Turn the back of every receipt into a revenue opportunity. Our Back Print Thermal Rolls let you pre-print coupons, legal disclosures, loyalty program details, or brand messaging on the reverse side — at no extra print cost to your customer.",
    description: "Back print thermal paper combines a thermal-sensitive front face with approved reverse-side artwork for disclosures, coupons, loyalty content, QR codes, or brand messaging. Front-face sensitivity, image density, retention, curl, and feed behavior depend on the selected grade, ink coverage, drying, rewinding, storage, and printer settings. The buyer should approve artwork proofs and production-intent samples before bulk printing; available widths, colors, order quantity, and schedule are confirmed after material and process review.",
    keywords: "back print thermal paper, pre-printed thermal rolls, thermal paper back printing, reverse print receipt paper, coupon thermal paper, regulatory disclosure receipt paper, back printed ATM paper",
    sizes: ["57×38mm", "57×40mm", "57×50mm", "80×50mm", "80×60mm", "80×70mm", "80×80mm", "82.5×80mm", "Custom"],
    applications: ["ATM & banking receipts", "Retail POS coupons", "Restaurant & hospitality", "Healthcare patient records", "Parking & transit tickets"],
    features: [
      "Pre-printed reverse side — coupons, disclosures, QR codes, or brand messaging",
      "Front thermal performance checked after ink, coverage, paper grade, and rewinding are approved",
      "Full-color back print with Pantone color matching available",
      "Ideal for regulatory compliance: banking T&Cs, healthcare patient rights",
      "Drives repeat business: loyalty rewards, promotional coupons, survey links",
      "Standard and custom widths confirmed after printer, artwork, tooling, and quantity review",
    ],
    moq: "Confirmed by specification, print, packing, and quantity",
    specifications: {
      "Grammage (GSM)": "55g / 60g / 65g",
      "Thickness": "65μm – 80μm",
      "Brightness (Front)": "≥ 92%",
      "Image Life (Front)": "Selected by grade and validated for storage and exposure conditions",
      "Back Print Method": "Flexographic / Offset printing",
      "Back Print Colors": "1–4 colors (full color available)",
      "Pantone Matching": "Available on request",
      "BPA Status": "BPA-free route available by selected grade and current document review",
      "Core Options": "Plastic / Cardboard (12mm, 17mm, 25mm)",
      "Min. Order Qty": "Confirmed by specification, print, packing, and quantity",
      "Lead Time": "Confirmed after specification, artwork, sample, and capacity review",
      "Documents": "Available documents reviewed by quoted product, destination, scope, and validity",
    },
    tag: "New",
  },
];

export const THERMAL_LABELS = [
  {
    slug: "direct-thermal-labels",
    name: "Direct Thermal Labels",
    subtitle: "No Ribbon Required — Shipping & Logistics Grade",
    heroDesc: "Direct thermal labels configured by printer, label size, roll or fanfold format, surface, barcode requirement, and service environment.",
    description: "Direct thermal labels for shipping, e-commerce fulfillment, warehouse identification, and retail workflows. The approved specification should define the printer, dimensions, core or fanfold stack, winding, carton or mailer surface, adhesive, barcode symbology, scanner target, handling, and retention requirement. GS1, carrier, and marketplace formats are produced from the buyer's approved data and template. Samples support feed, print-density, barcode, abrasion, adhesion, and pack validation before bulk production.",
    keywords: "direct thermal labels bulk, DT labels supplier, shipping labels 4x6, Zebra compatible labels, 100x150mm thermal labels wholesale, Amazon FBA labels, Zebra GX430t labels, GS1 barcode labels, DHL shipping labels, ecommerce fulfillment labels, 3PL thermal labels Europe",
    sizes: ["55×25mm", "60×40mm", "75×50mm", "100×50mm", "100×150mm", "4×6 inch", "Custom"],
    applications: ["Amazon FBA fulfillment", "E-commerce shipping", "3PL warehouse operations", "Retail pricing", "Logistics & distribution"],
    features: [
      "Model-based fit check for Zebra, Honeywell, SATO, Dymo, and other printers",
      "Image-retention grade selected for the handling and storage requirement",
      "GS1-128, SSCC, and other barcode formats produced from approved data",
      "Carrier and marketplace layouts produced from the buyer's current template",
      "Direct thermal printing avoids a ribbon in compatible workflows",
      "Roll and fanfold formats configured for the named printer or applicator",
    ],
    moq: "Confirmed by construction, tooling, packing, and quantity",
    specifications: {
      "Facestock": "Thermal-sensitive paper (white / yellow)",
      "Adhesive": "Permanent acrylic (standard) / Removable (optional)",
      "Liner": "Glassine / PE",
      "Label Format": "Roll / Fanfold",
      "Print Method": "Direct Thermal (no ribbon required)",
      "Print Speed": "Validated with the printer, ribbon-free grade, and barcode target",
      "Barcode Formats": "GS1-128, GS1 DataMatrix, SSCC, Code 128, QR by approved artwork",
      "Image Life": "Selected for the required handling and storage period",
      "Printer Fit": "Confirmed by model, dimensions, sensing, and sample",
      "Carrier Layouts": "Produced from the buyer's current approved template",
      "Min. Order Qty": "Confirmed by construction, tooling, packing, and quantity",
      "Lead Time": "Confirmed after specification, artwork, sample, and capacity review",
      "Documents": "Available documents reviewed by quoted product, destination, scope, and validity",
    },
    priority: "P1",
  },
  {
    slug: "thermal-transfer-labels",
    name: "Thermal Transfer Labels",
    subtitle: "Durable Long-Life Labels",
    heroDesc: "Thermal transfer label constructions selected by facestock, ribbon, adhesive, abrasion, UV, chemical exposure, and service-life requirements.",
    description: "Thermal transfer labels for industrial assets, outdoor equipment, and chemical-handling workflows. Finished durability depends on the facestock, ribbon, adhesive, topcoat or overlaminate, print settings, application surface, and named exposure conditions. Paper, polyester, and polypropylene constructions are available subject to project review and should be tested against the buyer's chemical, UV, abrasion, temperature, and readability criteria before approval.",
    keywords: "thermal transfer labels, TT labels manufacturer",
    sizes: ["55×25mm", "60×40mm", "75×50mm", "100×50mm", "100×150mm", "Custom"],
    applications: ["Industrial assets", "Outdoor use", "Chemical exposure"],
    features: [
      "Ribbon and facestock selected for the named chemical, UV, and abrasion tests",
      "Available on paper, polyester, and polypropylene facestocks",
      "Outdoor durability validated by facestock, ribbon, overlaminate, and exposure conditions",
      "Multiple adhesive options including high-tack and low-temperature",
    ],
    moq: "Confirmed by construction, tooling, packing, and quantity",
    specifications: {
      "Facestock": "Paper / Polyester (PET) / Polypropylene (PP)",
      "Adhesive": "Permanent / High-tack / Low-temperature",
      "Liner": "Glassine / PE / PET",
      "Label Format": "Roll",
      "Print Method": "Thermal Transfer (ribbon required)",
      "Outdoor Durability": "Validated for the selected material, ribbon, and exposure",
      "Min. Order Qty": "Confirmed by construction, tooling, packing, and quantity",
      "Lead Time": "Confirmed after specification, artwork, sample, and capacity review",
      "Documents": "Available documents reviewed by quoted product, site, scope, and validity",
    },
  },
  {
    slug: "high-temperature-labels",
    name: "High Temperature Labels",
    subtitle: "Heat-Resistant Industrial Labels",
    heroDesc: "High-temperature label constructions selected by peak temperature, dwell time, thermal cycles, surface, process chemicals, and barcode requirement.",
    description: "Label materials for automotive, electronics, and industrial processes with elevated-temperature exposure. The correct facestock and adhesive depend on the application surface, peak and continuous temperature, dwell time, thermal cycles, cleaning or process chemicals, print method, and required readability. Polyimide and aluminum-foil options are available subject to project review. Samples should be tested through the buyer's actual heat and handling process before production approval.",
    keywords: "high temp labels, heat resistant labels 150C",
    sizes: ["55×25mm", "60×40mm", "75×50mm", "100×50mm", "Custom"],
    applications: ["Automotive parts", "Electronics manufacturing", "Industrial processes"],
    features: [
      "Temperature range selected by peak, continuous exposure, and dwell time",
      "Adhesive system validated through the required thermal cycles",
      "Polyimide and aluminum-foil facestock options for project review",
      "Application samples recommended for delamination, bubbling, and print checks",
    ],
    moq: "Confirmed by construction, tooling, packing, and quantity",
    specifications: {
      "Facestock": "Polyimide (Kapton) / Aluminum Foil",
      "Adhesive": "Specialized acrylic (high-temp)",
      "Temperature Range": "Confirmed by material, dwell time, and process",
      "Thermal Cycling": "Validated against the buyer's cycle profile",
      "Label Format": "Roll",
      "Min. Order Qty": "Confirmed by construction, tooling, packing, and quantity",
      "Lead Time": "Confirmed after specification, artwork, sample, and capacity review",
      "Documents": "Available documents reviewed by quoted product, site, scope, and validity",
    },
    tag: "SEO",
  },
  {
    slug: "freezer-cold-chain-labels",
    name: "Freezer & Cold Chain Labels",
    subtitle: "Cryo & Freeze Labels",
    heroDesc: "Cold-chain labels selected by application temperature, service temperature, freeze-thaw exposure, surface, moisture, printer, and documentation needs.",
    description: "Label constructions for frozen food, temperature-controlled logistics, and laboratory or pharmaceutical workflows. Material selection depends on whether the label is applied before or after freezing, the packaging surface, minimum application temperature, service temperature, condensation, freeze-thaw cycles, print method, and required documentation. Low-temperature adhesives and moisture-resistant facestocks are available subject to project review. Samples should be tested on the actual surface through the intended cold-chain cycle.",
    keywords: "freezer labels, cryo labels, cold chain adhesive labels, -40C freezer labels, FDA cold chain labels, frozen food labels wholesale",
    sizes: ["55×25mm", "60×40mm", "75×50mm", "100×50mm", "Custom"],
    applications: ["Frozen food", "Pharmaceutical cold chain", "Lab specimens"],
    features: [
      "Application and service temperature matched to the adhesive grade",
      "Freeze-thaw adhesion validated on the buyer's packaging surface",
      "Moisture-resistant facestock options for condensation exposure",
      "Material documents supplied according to the selected construction and destination review",
    ],
    moq: "Confirmed by construction, tooling, packing, and quantity",
    specifications: {
      "Facestock": "Moisture-resistant paper / PP",
      "Adhesive": "Low-temperature acrylic",
      "Temperature Range": "Confirmed by adhesive, surface, and application method",
      "Freeze-Thaw Cycles": "Validated on the intended surface and cycle profile",
      "Label Format": "Roll",
      "Min. Order Qty": "Confirmed by construction, tooling, packing, and quantity",
      "Lead Time": "Confirmed after specification, artwork, sample, and capacity review",
      "Documents": "Available documents reviewed by quoted product, site, scope, and validity",
    },
    tag: "SEO",
  },
  {
    slug: "removable-labels",
    name: "Removable Labels",
    subtitle: "Clean Peel Labels",
    heroDesc: "Removable labels selected by surface, dwell time, temperature, reuse expectation, and acceptable residue or surface-change criteria.",
    description: "Temporary labels for retail pricing, short-term identification, reusable packaging, and controlled removal workflows. Clean removal depends on the substrate, coating, surface energy, temperature, dwell time, pressure, and aging conditions. Paper and synthetic facestocks with removable adhesive options are available subject to project review. Buyers should test samples on every intended surface and after the full dwell period before approving production.",
    keywords: "removable thermal labels, clean peel labels",
    sizes: ["55×25mm", "60×40mm", "75×50mm", "100×50mm", "Custom"],
    applications: ["Retail price tags", "Temporary marking", "Reusable packaging"],
    features: [
      "Removal performance validated by surface, dwell time, and temperature",
      "Repositionable options available subject to adhesive and surface testing",
      "Paper and synthetic facestocks selected for the intended environment",
      "Sample testing recommended on glass, plastic, metal, and coated board",
    ],
    moq: "Confirmed by construction, tooling, packing, and quantity",
    specifications: {
      "Facestock": "Thermal-sensitive paper (white)",
      "Adhesive": "Removable acrylic (clean peel)",
      "Liner": "Glassine",
      "Label Format": "Roll / Fanfold",
      "Print Method": "Direct Thermal",
      "Min. Order Qty": "Confirmed by construction, tooling, packing, and quantity",
      "Lead Time": "Confirmed after specification, artwork, sample, and capacity review",
      "Documents": "Available documents reviewed by quoted product, site, scope, and validity",
    },
  },
  {
    slug: "synthetic-paper-labels",
    name: "Synthetic PP Labels",
    subtitle: "Moisture & Tear-Resistant Label Options",
    heroDesc: "Synthetic PP label constructions selected by moisture, abrasion, UV, chemical, print-method, and service-life requirements.",
    description: "Polypropylene label materials for applications where paper may not provide enough moisture or tear resistance. The finished performance depends on the PP facestock, topcoat, adhesive, ink or ribbon, overlaminate, exposure, and application surface. Clear and white options can be configured for compatible direct thermal or thermal transfer workflows. Samples should be tested for water exposure, abrasion, UV, adhesion, and print durability under the intended conditions.",
    keywords: "synthetic paper labels, waterproof PP labels",
    sizes: ["55×25mm", "60×40mm", "75×50mm", "100×50mm", "100×150mm", "Custom"],
    applications: ["Outdoor assets", "Chemical containers", "Marine use"],
    features: [
      "Water resistance validated for the material, print system, and exposure time",
      "Tear-resistant polypropylene facestock options for handling stress",
      "Outdoor durability confirmed by UV exposure and finished construction",
      "Clear and white options for compatible direct thermal or thermal transfer use",
    ],
    moq: "Confirmed by construction, tooling, packing, and quantity",
    specifications: {
      "Facestock": "Polypropylene (PP) synthetic",
      "Adhesive": "Permanent acrylic",
      "Liner": "PE / PET",
      "Resistance": "Validated for moisture, tear, print, and exposure requirements",
      "Label Format": "Roll",
      "Min. Order Qty": "Confirmed by construction, tooling, packing, and quantity",
      "Lead Time": "Confirmed after specification, artwork, sample, and capacity review",
      "Documents": "Available documents reviewed by quoted product, site, scope, and validity",
    },
  },
  {
    slug: "tamper-evident-labels",
    name: "Tamper-Evident Labels",
    subtitle: "Security & Void Labels",
    heroDesc: "Tamper-evident constructions selected by surface, removal behavior, residue pattern, destructibility, artwork, and authentication workflow.",
    description: "Security labels for electronics, regulated packaging, high-value goods, and other controlled-opening applications. Available constructions can reveal a VOID pattern, destruct on removal, or combine security print, sequential numbering, and QR codes. Tamper evidence depends on the label construction, application surface, dwell time, temperature, and removal method. Buyers should test samples on the actual package and define the expected evidence pattern before production approval.",
    keywords: "tamper evident labels wholesale, security labels",
    sizes: ["55×25mm", "60×40mm", "75×50mm", "100×50mm", "Custom"],
    applications: ["Electronics", "Pharmaceuticals", "High-value goods"],
    features: [
      "VOID-pattern options validated on the intended packaging surface",
      "Destructible facestock options for visible removal evidence",
      "Custom security print, sequential numbering, and QR code options",
      "Security construction reviewed against the buyer's control requirement",
    ],
    moq: "Confirmed by construction, tooling, packing, and quantity",
    specifications: {
      "Facestock": "Destructible vinyl / VOID material",
      "Adhesive": "Permanent (tamper-evident)",
      "Tamper Feature": "VOID pattern on removal",
      "Label Format": "Roll",
      "Min. Order Qty": "Confirmed by construction, tooling, packing, and quantity",
      "Lead Time": "Confirmed after specification, artwork, sample, and capacity review",
      "Documents": "Available documents reviewed by quoted product, site, scope, and validity",
    },
    tag: "New",
  },
  {
    slug: "chemical-resistant-labels",
    name: "Chemical Resistant Labels",
    subtitle: "Chemical & Solvent Resistant",
    heroDesc: "Chemical-resistant label constructions selected by named chemicals, concentration, contact time, temperature, sterilization cycle, and readability target.",
    description: "Polyester and protected label constructions for laboratories, chemical storage, industrial fluids, and cleaning-intensive workflows. Resistance depends on the facestock, adhesive, print system, overcoat, chemical, concentration, contact time, temperature, and cycle count. GHS or CLP content is produced from the buyer's approved hazard data and artwork; material selection alone does not establish finished-label compliance. Samples should be exposed to the actual process before production approval.",
    keywords: "chemical resistant labels, solvent resistant labels",
    sizes: ["55×25mm", "60×40mm", "75×50mm", "100×50mm", "Custom"],
    applications: ["Lab specimens", "Chemical storage", "Industrial fluids"],
    features: [
      "Chemical resistance validated by substance, concentration, contact time, and temperature",
      "Sterilization compatibility reviewed against the buyer's cycle profile",
      "Polyester and protective overcoat options for chemical-exposure testing",
      "GHS or CLP artwork produced from the buyer's approved hazard information",
    ],
    moq: "Confirmed by construction, tooling, packing, and quantity",
    specifications: {
      "Facestock": "Polyester (PET)",
      "Adhesive": "Autoclave-compatible acrylic",
      "Chemical Resistance": "Validated against the named substance and exposure profile",
      "Sterilization": "Reviewed against the buyer's temperature, dwell time, and cycles",
      "Label Format": "Roll",
      "Hazard Artwork": "GHS / CLP content from buyer-approved data",
      "Min. Order Qty": "Confirmed by construction, tooling, packing, and quantity",
      "Lead Time": "Confirmed after specification, artwork, sample, and capacity review",
      "Documents": "Available documents reviewed by quoted product, site, scope, and validity",
    },
    tag: "New",
  },
  {
    slug: "wristband-labels",
    name: "Wristband Labels",
    subtitle: "Hospital & Event Wristbands",
    heroDesc: "Wristband stock configured by printer, wearer group, wear time, closure, water exposure, barcode requirement, and skin-contact review.",
    description: "Thermal wristbands for patient identification, events, attractions, and controlled access. The approved construction should define the printer model, wristband dimensions, wearer group, wear duration, closure behavior, water or cleaning exposure, barcode requirement, and skin-contact documentation. Synthetic and tamper-evident options are available subject to project review. Samples should be tested for print, scanning, closure, comfort, and removal in the intended workflow.",
    keywords: "thermal wristband labels, hospital wristband rolls",
    sizes: ["25×254mm", "25×279mm", "Custom"],
    applications: ["Hospitals", "Events", "Theme parks"],
    features: [
      "Skin-contact documentation available by selected material",
      "Water and cleaning exposure validated for the required wear period",
      "Tamper-evident closure options reviewed against the access workflow",
      "Printer fit confirmed by model, dimensions, sensing, and sample",
    ],
    moq: "Confirmed by construction, tooling, packing, and quantity",
    specifications: {
      "Facestock": "Synthetic material selected for the required water-exposure test",
      "Skin Contact": "Material documentation supplied by selected construction",
      "Closure": "Tamper-evident option, validated in the intended workflow",
      "Water Resistance": "Validated against exposure and wear duration",
      "Label Format": "Roll",
      "Min. Order Qty": "Confirmed by construction, tooling, packing, and quantity",
      "Lead Time": "Confirmed after specification, artwork, sample, and capacity review",
      "Documents": "Available documents reviewed by quoted product, site, scope, and validity",
    },
    tag: "New",
  },
  {
    slug: "fanfold-labels",
    name: "Fanfold Labels",
    subtitle: "Z-Fold Bulk Labels",
    heroDesc: "Fanfold labels configured by printer path, stack dimensions, fold pitch, sensing, perforation, label size, adhesive, and pallet plan.",
    description: "Z-fold label stock for high-volume shipping, warehouse, and e-commerce workflows. Smooth feeding depends on the printer, rear-feed path, stack height, fold direction, perforation, liner stiffness, sensing method, and storage conditions. Common shipping sizes and custom formats are available subject to die and equipment review. Production-intent samples allow buyers to verify feeding, separation, print registration, barcode readability, and stack behavior before pallet supply.",
    keywords: "fanfold labels, 2-fold labels bulk",
    sizes: ["100×150mm", "4×6 inch", "Custom"],
    applications: ["High-volume shipping", "Warehouse operations", "E-commerce"],
    features: [
      "Fold pitch and stack dimensions configured for the named printer path",
      "Large-stack format can reduce roll changes in compatible workflows",
      "Perforation and liner selected for the required separation behavior",
      "Bulk pallet packing available after stack and carton approval",
    ],
    moq: "Confirmed by construction, tooling, packing, and quantity",
    specifications: {
      "Facestock": "Thermal-sensitive paper",
      "Adhesive": "Permanent acrylic",
      "Liner": "Glassine",
      "Label Format": "Fanfold (Z-fold)",
      "Perforation": "Optimised for clean separation",
      "Print Method": "Direct Thermal",
      "Min. Order Qty": "Confirmed by construction, tooling, packing, and quantity",
      "Lead Time": "Confirmed after specification, artwork, sample, and capacity review",
      "Documents": "Available documents reviewed by quoted product, site, scope, and validity",
    },
  },
  {
    slug: "custom-printed-labels",
    name: "Custom Printed Labels",
    subtitle: "Private Label Thermal",
    heroDesc: "Custom printed labels configured by artwork, facestock, adhesive, die, variable data, application, packing, and destination-document requirements.",
    description: "Private-label and custom-printed labels with full-color printing, die cutting, variable data, serialization, and branded packing options. Material selection depends on the application surface, print method, environment, contact conditions, and destination documentation. BPA-free, phenol-free, and food-contact-document routes may be available for selected constructions subject to review. Artwork proofs and production-intent samples are approved before volume manufacture.",
    keywords: "custom printed labels, private label thermal",
    sizes: ["55×25mm", "60×40mm", "75×50mm", "100×50mm", "100×150mm", "Custom"],
    applications: ["Brand labels", "Product identification", "Custom packaging"],
    features: [
      "Full-color printing with Pantone color matching available",
      "Custom die cutting subject to geometry, material, and tooling review",
      "Variable data and serialization from buyer-approved data rules",
      "Material-document options supplied by selected construction and destination review",
    ],
    moq: "Confirmed by construction, tooling, packing, and quantity",
    specifications: {
      "Facestock": "Paper / PP / PET (customer choice)",
      "Adhesive": "Permanent / Removable / Freezer (customer choice)",
      "Printing": "Full-color (Pantone matching available)",
      "Die-Cutting": "Custom geometry subject to material and tooling review",
      "Variable Data": "Serialization, QR code, barcode",
      "Min. Order Qty": "Confirmed by construction, tooling, packing, and quantity",
      "Lead Time": "Confirmed after specification, artwork, sample, and capacity review",
      "Documents": "Available documents reviewed by quoted construction, intended use, destination, and validity",
    },
  },
];

export const INDUSTRIES = [
  {
    slug: "retail-pos",
    name: "Retail & POS",
    icon: "ShoppingCart",
    description: "Thermal receipt paper for retail chains, supermarkets, restaurants, and POS distributors. Buyers can select BPA-free, BPS-free, or phenol-free grades according to the destination requirement and available material documents. Back-print options support approved coupons, loyalty messaging, disclosures, and QR codes. Printer fit for Epson TM-series, Star TSP-series, Bixolon, and other devices is confirmed by the exact model, roll dimensions, core, winding, and approved sample rather than brand name alone.",
    keywords: "POS receipt paper supplier, thermal paper retail wholesale, 80mm POS paper rolls, receipt paper bulk order, 57mm thermal rolls, BPA free receipt paper EU, phenol free thermal paper, Blauer Engel thermal paper, back print receipt paper, Epson compatible thermal rolls",
    products: ["Standard POS Rolls", "Custom Printed Rolls", "Back Print Thermal Rolls"],
    priority: "P1",
  },
  {
    slug: "lottery-gaming",
    name: "Lottery & Gaming",
    icon: "Ticket",
    description: "Thermal ticket stock for lottery terminals, TITO slot machines, gaming kiosks, and betting-shop printers. Projects are configured around the named terminal, ticket width, core, black-mark or gap-sensing layout, barcode requirement, retention target, and storage conditions. Available security-print options can include watermarks, UV-visible inks, microtext, and sequential numbering, subject to artwork and process review. Buyers can request batch identification, controlled packing, and production-intent samples to validate feed accuracy, sensor response, print density, scanner readability, and ticket handling before bulk approval. Platform fit and security-control requirements are confirmed against the project specification rather than inferred from a brand name alone.",
    keywords: "lottery thermal paper supplier, TITO paper manufacturer, gaming machine paper rolls, lottery ticket paper wholesale, casino slot paper supplier, IGT compatible thermal paper, Scientific Games ticket paper, Intralot terminal paper, betting shop paper rolls, barcode thermal paper lottery, security print thermal paper, anti-counterfeit lottery paper, WLA compliant paper rolls, TITO cash voucher paper, gaming kiosk paper rolls, lottery terminal paper manufacturer",
    products: ["Lottery Gaming Rolls", "Casino TITO Rolls"],
    tag: "SEO",
  },
  {
    slug: "casino",
    name: "Casino",
    icon: "Coins",
    description: "TITO ticket stock for casino slot machines and gaming terminals, configured around the printer path, ticket width, core, barcode requirement, image-retention target, and storage conditions. Buyers can validate print density, cut consistency, paper curl, sensor marks, and carton identification with production-intent samples before approving a bulk specification. Platform compatibility and retention requirements are confirmed against the named machine model and project documents rather than assumed from the paper grade alone.",
    keywords: "casino TITO paper supplier, slot machine ticket stock, gaming terminal thermal paper, casino barcode ticket rolls, TITO roll specification",
    products: ["Casino TITO Rolls"],
    tag: "SEO",
  },
  {
    slug: "banking-finance",
    name: "Banking & Finance",
    icon: "Building2",
    description: "ATM and banking receipt rolls configured for the named terminal, transaction-record workflow, image-retention target, anti-static requirement, and approved disclosure copy. Available options include controlled back printing, batch identification, protective packing, and production samples for checking paper path, cut performance, print density, and long-term image stability under the buyer's storage conditions. Retention and regulatory suitability depend on the selected grade, storage environment, and project review.",
    keywords: "ATM receipt paper supplier, bank thermal paper rolls, back print thermal paper, transaction receipt rolls, ATM paper specification",
    products: ["ATM & Bank Receipt Rolls", "Back Print Thermal Rolls"],
    tag: "SEO",
  },
  {
    slug: "healthcare-pharma",
    name: "Healthcare & Pharma",
    icon: "Heart",
    description: "Thermal rolls and labels for hospitals, pharmacies, clinical laboratories, and medical consumables distributors. The specification should identify the patient or specimen workflow, contact surface, printer, retention target, storage temperature, cleaning chemicals, and required material documents. Available grades include BPA-free roll stock, wristband formats, and freezer-label constructions, subject to project review and sample validation. Buyers can test print stability, adhesion, scanning, and handling in their actual workflow before approving a production material; regulatory and symbol requirements remain tied to the finished device, destination market, and approved documentation.",
    keywords: "medical thermal paper phenol options, hospital receipt paper, pharmacy label manufacturer, medical material document review, destination-specific medical label requirements, low-temperature specimen labels, specimen tube labels, patient wristband labels, buyer-approved medical symbols, thermal paper record retention review",
    products: ["Medical Rolls", "Wristband Labels", "Freezer Cold Chain Labels"],
    tag: "SEO",
  },
  {
    slug: "food-cold-chain",
    name: "Food & Cold Chain",
    icon: "Snowflake",
    description: "Thermal labels for food processing, cold storage, supermarket, and temperature-controlled logistics workflows. The correct construction depends on the minimum application temperature, service temperature, freeze-thaw exposure, packaging surface, moisture, printer, barcode format, and destination-market documents. Available options include permanent or removable adhesives, direct thermal or thermal transfer facestocks, and roll or fanfold formats. Buyers should validate adhesion, print durability, barcode readability, migration or food-contact documentation where relevant, and packing performance with a production-intent sample. GS1 and traceability requirements are implemented from the buyer's approved data and label specification.",
    keywords: "freezer label construction review, food contact document thermal labels, cold chain labels wholesale, food processing label workflow, EU food contact document requirements, US food contact document review, chain-of-custody paper options, low-temperature label validation, frozen food labels bulk, cold storage barcode labels, GS1-128 food traceability artwork, FSMA 204 data field review, food label supplier documentation, freeze-thaw labels, Zebra freezer label model fit check, fanfold food labels, food processing thermal labels, supermarket deli labels, reefer cargo labels",
    products: ["Freezer Cold Chain Labels", "Direct Thermal Labels", "Fanfold Labels"],
    tag: "SEO",
  },
  {
    slug: "logistics-warehouse",
    name: "Logistics & Warehouse",
    icon: "Package",
    description: "Direct thermal shipping, pallet, and bin labels for 3PLs, fulfillment centers, distribution hubs, and warehouse integrators. Buyers should specify the printer or applicator, label dimensions, roll or fanfold format, carton or bin surface, barcode symbology, scanner requirement, storage conditions, and expected service life. Available constructions include permanent and removable adhesives for common logistics surfaces. Production-intent samples allow teams to check feeding, print density, barcode grading, adhesion, abrasion, and stack or roll dimensions before volume approval.",
    keywords: "shipping labels bulk supplier, warehouse thermal labels, 4x6 shipping labels wholesale, fanfold labels manufacturer, Zebra compatible labels, 3PL thermal labels, GS1 SSCC barcode labels, Zebra ZPL labels Europe, warehouse bin labels bulk, DHL Hermes DPD compatible labels",
    products: ["Direct Thermal Labels", "Fanfold Labels", "Direct Thermal Rolls"],
  },
  {
    slug: "ecommerce",
    name: "E-Commerce & Fulfillment",
    icon: "ShoppingCart",
    description: "Thermal shipping and product-identification labels for marketplace sellers, DTC brands, and fulfillment centers. Common formats include 4×6 shipping labels, smaller product labels, pallet labels, and roll or fanfold stock, but the approved dimensions must come from the marketplace, carrier, printer, and workflow. The label construction is selected for the carton, poly mailer, or other packaging surface and the expected handling conditions. Buyers can validate feeding, print density, barcode readability, abrasion, adhesion, and pack configuration with production-intent samples before placing a volume order.",
    keywords: "ecommerce shipping labels wholesale, 4x6 thermal labels Amazon FBA, FNSKU labels bulk, Shopify shipping labels bulk, fulfillment center labels supplier, 3PL thermal labels, direct thermal labels e-commerce, Zebra GX430t labels, Amazon FBA label requirements, DHL shipping labels bulk, fanfold labels fulfillment, GS1-128 barcode labels, SSCC pallet labels, 100x150mm shipping labels",
    products: ["Direct Thermal Labels", "Fanfold Labels", "Custom Printed Rolls"],
    tag: "New",
  },
  {
    slug: "transportation",
    name: "Transportation",
    icon: "Bus",
    description: "Thermal ticket and receipt media for parking, transit, tolling, and passenger-service systems. The specification is built from the machine model, ticket dimensions, black-mark or gap-sensing requirement, barcode format, exposure conditions, retention period, and packing plan. Production-intent samples allow operators and integrators to check feed accuracy, cutting, sensor response, scanner readability, and outdoor handling before approving volume supply.",
    keywords: "parking ticket paper supplier, transit thermal ticket rolls, toll receipt paper, black mark ticket stock, transport ticket paper manufacturer",
    products: ["Transport Ticket Rolls", "Parking Ticketing Rolls"],
    tag: "New",
  },
  {
    slug: "automotive-industrial",
    name: "Automotive & Industrial",
    icon: "Wrench",
    description: "Thermal and thermal-transfer labels for automotive parts, industrial manufacturing, warehouse identification, and work-in-process tracking. Material selection depends on the substrate, surface texture, temperature profile, chemical and abrasion exposure, barcode requirement, and application method. Available constructions include paper and synthetic facestocks with permanent or high-tack adhesives. Where a customer workflow references VDA, OEM, or other industry formats, the finished label is produced from the buyer's approved drawing and data specification. Exposure and adhesion claims should be confirmed with application samples under the intended process conditions.",
    keywords: "automotive thermal labels VDA 4902, industrial labels chemical resistant, BMW VW supplier labels, high temperature labels 150C, factory floor labels, parts tracking labels, synthetic thermal labels, polyester labels manufacturer, industrial barcode labels Europe",
    products: ["Chemical Resistant Labels", "High Temperature Labels", "Direct Thermal Labels"],
    tag: "New",
  },
  {
    slug: "events-hospitality",
    name: "Events & Hospitality",
    icon: "Calendar",
    description: "Ticket stock, wristband labels, and custom-printed thermal media for venues, attractions, restaurants, and hospitality campaigns. Projects are specified around the printer, ticket or label dimensions, barcode or QR contrast, handling duration, artwork colors, launch date, and pack format. A proof and production-intent sample help teams verify scan performance, color targets, stock thickness, and finishing before the event schedule is locked.",
    keywords: "event ticket paper supplier, thermal wristband labels, venue ticket rolls, QR ticket paper, custom printed hospitality rolls",
    products: ["Wristband Labels", "Custom Printed Rolls"],
    tag: "New",
  },
  {
    slug: "government-legal",
    name: "Government & Legal",
    icon: "Scale",
    description: "Thermal receipt and record media for public counters, municipal services, court-support workflows, and legal offices. Procurement should begin with the record type, required retention period, named printer, roll dimensions, approved disclosure copy, security or back-print needs, and document-control process. Because thermal image life depends on the coating and storage environment, long-term or evidentiary records require project-specific review and may need an alternative print technology. Samples and material documents are provided for buyer validation before bulk production.",
    keywords: "government receipt paper supplier, public service thermal rolls, legal office receipt paper, controlled back print rolls, record retention thermal paper",
    products: ["Medical Rolls", "Standard POS Rolls", "Back Print Thermal Rolls"],
    tag: "New",
  },
  {
    slug: "cannabis-specialty",
    name: "Cannabis & Specialty",
    icon: "Leaf",
    description: "Custom thermal and tamper-evident labels for regulated specialty retail, dispensary operations, and packaging converters. Label content and construction must be reviewed for the destination jurisdiction, container surface, required variable data, barcode format, warning or batch fields, and tamper-evident need. Zhixin Paper supplies configurable materials and controlled artwork revisions; regulatory approval remains with the buyer and its qualified adviser. Production-intent samples support adhesion, scanning, print durability, and application testing before volume manufacture.",
    keywords: "cannabis packaging labels supplier, dispensary thermal labels, tamper evident specialty labels, variable data compliance labels, regulated retail label manufacturer",
    products: ["Tamper Evident Labels", "Custom Printed Labels", "Direct Thermal Labels"],
    tag: "New",
  },
];

export const GEO_REGIONS = [
  {
    slug: "eu",
    name: "Europe",
    flag: "🇪🇺",
    description: "Thermal paper rolls and labels for European distributors and importers. Material chemistry, REACH or RoHS scope, food-contact use, chain-of-custody needs, and supporting documents are reviewed against the exact quoted grade and destination.",
    keywords: "thermal paper supplier Europe, BPA free rolls EU, REACH documentation thermal paper, thermal labels EU wholesale",
    priority: "P1",
    compliance: ["Phenol options by grade", "REACH/RoHS document review", "Quality-system documents", "Chain-of-custody options", "Food-contact scope review"],
    shipping: "FOB, CIF, or destination-specific delivered terms quoted after route and responsibility review",
    countries: [
      {
        slug: "germany",
        name: "Germany",
        flag: "🇩🇪",
        lang: "DE",
        keywords: "Thermopapier Lieferant, Etiketten Hersteller Deutschland, Kassenrollen Großhandel, BPA-freies Thermopapier Deutschland",
        description: "Thermal rolls and labels for German distributors, retail programs, logistics operations, and equipment channels. Buyers should confirm material chemistry, document language, printer fit, packing, and the applicable regulatory scope before approval.",
        compliance: ["Phenol grade review", "REACH document review", "Quality-system documents", "Chain-of-custody options"],
        shipping: "Hamburg routing and Incoterm options quoted for the confirmed shipment plan",
        port: "Hamburg (HH)",
        leadTime: "Confirmed after specification, capacity, and booking review",
        highlights: [
          "German-language documents reviewed for the selected material and project scope",
          "BPA-free, BPS-free, or phenol-free routes available by quoted grade",
          "Printer fit confirmed by model, dimensions, winding, and approved sample",
          "Packing and pallet plan agreed for the receiving warehouse",
          "Quality-system and material documents supplied according to the approved project",
        ],
        popularProducts: ["Standard POS Rolls 80×80mm", "Thermal Labels 100×150mm", "ATM Bank Receipt Rolls"],
      },
      {
        slug: "uk",
        name: "United Kingdom",
        flag: "🇬🇧",
        lang: "EN",
        keywords: "thermal paper supplier UK, thermal till rolls wholesale Britain, receipt paper rolls UK, thermal labels wholesale UK, till rolls bulk order",
        description: "Thermal till rolls and labels for UK distributors, retail, hospitality, and logistics programs. Procurement should confirm the exact grade, UK document scope, dimensions, packing, Incoterm, and import responsibilities before production.",
        compliance: ["Phenol grade review", "UK REACH document review", "Quality-system documents", "Chain-of-custody options"],
        shipping: "Felixstowe or Southampton routing quoted after shipment and Incoterm review",
        port: "Felixstowe / Southampton",
        leadTime: "Confirmed after specification, capacity, and booking review",
        highlights: [
          "UK REACH document scope reviewed against the selected material",
          "BPA-free, BPS-free, or phenol-free routes available by quoted grade",
          "Common UK till-roll sizes configured to the named printer",
          "Delivered terms may be quoted after customs, tax, and destination review",
          "English technical and material documentation supplied by project scope",
        ],
        popularProducts: ["Standard POS Rolls (Till Rolls)", "Direct Thermal Labels 4×6", "ATM Bank Receipt Rolls"],
      },
      {
        slug: "france",
        name: "France",
        flag: "🇫🇷",
        lang: "FR",
        keywords: "fournisseur papier thermique France, étiquettes thermiques France, rouleaux caisse enregistreuse, papier thermique BPA gratuit France",
        description: "Thermal rolls and labels for French distribution, retail, hospitality, food-label, and logistics projects. Material declarations, chain-of-custody needs, food-contact scope, and French-language documents are confirmed for the selected construction.",
        compliance: ["Phenol grade review", "REACH document review", "Quality-system documents", "Chain-of-custody options", "Food-contact scope review"],
        shipping: "Le Havre or Marseille routing quoted for the confirmed shipment plan",
        port: "Le Havre / Marseille",
        leadTime: "Confirmed after specification, capacity, and booking review",
        highlights: [
          "French-language documents reviewed for the selected material",
          "BPA-free, BPS-free, or phenol-free routes available by quoted grade",
          "Chain-of-custody paper options subject to supplier and SKU confirmation",
          "Food-contact documentation reviewed for the exact application and construction",
          "Pallet and container options quoted by SKU, quantity, and destination",
        ],
        popularProducts: ["Standard POS Rolls 80×80mm", "Thermal Labels", "Custom Printed Rolls"],
      },
      {
        slug: "netherlands",
        name: "Netherlands",
        flag: "🇳🇱",
        lang: "NL",
        keywords: "thermisch papier leverancier Nederland, thermische etiketten groothandel, kassarollen Nederland, BPA-vrij thermisch papier",
        description: "Thermal labels and receipt rolls for Dutch logistics, e-commerce, retail, and regional distribution projects. Rotterdam routing, warehouse packing, material scope, and documents are confirmed in the project quotation.",
        compliance: ["Phenol grade review", "REACH/RoHS document review", "Quality-system documents", "Chain-of-custody options"],
        shipping: "Rotterdam routing and onward-delivery responsibilities quoted by destination",
        port: "Rotterdam (RTM)",
        leadTime: "Confirmed after specification, capacity, and booking review",
        highlights: [
          "Rotterdam routing available subject to carrier and booking review",
          "Packing plans configured for distribution and warehouse handling",
          "Material chemistry and REACH scope confirmed for the quoted grade",
          "Shipping-label constructions selected by printer, surface, and environment",
          "Dutch-language documents reviewed when required by the project",
        ],
        popularProducts: ["Direct Thermal Labels 100×150mm", "Standard POS Rolls", "Fanfold Labels"],
      },
      {
        slug: "poland",
        name: "Poland",
        flag: "🇵🇱",
        lang: "PL",
        keywords: "dostawca papieru termicznego Polska, etykiety termiczne hurtownia, rolki kasowe Polska, papier termiczny BPA-free Polska",
        description: "Thermal paper and label supply for Polish retail, logistics, and distribution programs. Buyers can review grade options, EU material documents, local-language requirements, packing, and Gdańsk or alternative routing before approval.",
        compliance: ["Phenol grade review", "REACH document review", "Quality-system documents", "Chain-of-custody options"],
        shipping: "Gdańsk, Hamburg, or alternative routing quoted for the confirmed destination",
        port: "Gdańsk / Hamburg",
        leadTime: "Confirmed after specification, capacity, and booking review",
        highlights: [
          "Factory quotation based on dimensions, grade, packing, and volume",
          "BPA-free, BPS-free, or phenol-free routes available by quoted grade",
          "Polish-language documents reviewed when required by the project",
          "Gdańsk, Hamburg, and onward routing assessed with the forwarder",
          "Packing configured for Polish and Central European distribution programs",
        ],
        popularProducts: ["Standard POS Rolls", "Direct Thermal Labels", "Thermal Labels"],
      },
    ],
  },
  {
    slug: "us",
    name: "United States",
    flag: "🇺🇸",
    description: "Thermal paper rolls and labels for US distributors, importers, and e-commerce programs. Material chemistry, food-contact scope, California disclosure needs, printer fit, packing, and supporting documents are reviewed for the exact quoted product.",
    keywords: "thermal paper supplier USA, thermal labels wholesale America, food contact thermal paper document review, BPA free receipt paper USA, Prop 65 thermal paper review",
    priority: "P1",
    compliance: ["Food-contact scope review", "California disclosure review", "Phenol options by grade", "Quality-system documents", "Chain-of-custody options"],
    shipping: "FOB, CIF, or destination-specific delivered terms quoted after route, tariff, and responsibility review",
    highlights: [
      "Food-contact documentation reviewed for the exact material and intended use",
      "California chemical and warning scope reviewed by quoted grade",
      "Delivered terms may be quoted after destination, tariff, and customs review",
      "Pallet, LCL, and container plans quoted by SKU and volume",
      "Regulated label projects require buyer-approved state and application requirements",
      "Printer fit confirmed by model, dimensions, winding, sensing layout, and sample",
    ],
    subpages: [
      { slug: "fda-compliant", name: "US Food-Contact Review", keywords: "FDA thermal paper document review, BPA free thermal USA, 21 CFR thermal paper scope" },
      { slug: "cannabis-labels", name: "Cannabis Labels", keywords: "cannabis label supplier USA, dispensary thermal labels, state cannabis label review" },
    ],
  },
  {
    slug: "ca",
    name: "Canada",
    flag: "🇨🇦",
    description: "Thermal paper rolls and labels for Canadian distributors. Material chemistry, bilingual artwork, regulated-label requirements, destination responsibilities, and supporting documents are reviewed for the exact product and province.",
    keywords: "thermal paper supplier Canada, thermal labels wholesale Canada, BPA-free thermal paper Canada, Canadian material document review, cannabis labels Canada",
    compliance: ["Canadian material review", "Phenol options by grade", "Quality-system documents", "Regulated-label review", "CEPA scope review"],
    shipping: "Vancouver, Montreal, or alternative routing quoted after destination and Incoterm review",
    highlights: [
      "Canadian material and chemical scope reviewed for the selected grade",
      "Regulated-label projects require buyer-approved federal and provincial requirements",
      "English and French artwork or documents reviewed when required by the project",
      "North American and metric formats configured to the named printer and SKU",
      "Port, inland route, customs, tax, and responsibility allocation stated in the quotation",
      "OEM and private-label packing subject to artwork, quantity, and production review",
    ],
    subpages: [
      { slug: "cannabis-labels", name: "Cannabis Labels", keywords: "cannabis label review Canada, Health Canada label requirements, Cannabis Act labels" },
    ],
  },
];

export const COMPLIANCE_ITEMS = [
  { slug: "bpa-free", name: "BPA-Free & Phenol-Free", icon: "ShieldCheck", color: "emerald", description: "BPA-free, BPS-free, bisphenol-free, and phenol-free routes are confirmed by product and quoted paper grade. Buyers should request the grade name, named chemical scope, and supporting declaration or test report before approval." },
  { slug: "reach-rohs", name: "REACH/RoHS Review", icon: "FileCheck", color: "blue", description: "REACH substance scope and any RoHS relevance are reviewed against the exact material, intended application, destination, current candidate list, and available supplier documents." },
  { slug: "iso-9001", name: "Quality-System Documents", icon: "Award", color: "orange", description: "Available quality-system documents should be checked for the certificate holder, manufacturing site, covered activities, issuer, and current validity. Product inspection records are confirmed separately by project." },
  { slug: "fsc-paper", name: "Chain-of-Custody Options", icon: "Leaf", color: "green", description: "Chain-of-custody paper routes depend on the selected paper, supplier, production site, order scope, transaction documents, and approved claim use." },
  { slug: "eu-food-contact", name: "EU Food-Contact Review", icon: "UtensilsCrossed", color: "teal", description: "EU food-contact suitability is reviewed by complete construction, intended food, contact type, time, temperature, destination, and the scope of current declarations or tests." },
  { slug: "fda-us", name: "US Food-Contact Review", icon: "Shield", color: "red", description: "US food-contact projects require review of the exact paper, coating, adhesive, ink, intended conditions of use, applicable 21 CFR provisions, and current supporting documents." },
  { slug: "iso-15223", name: "Medical Label Review", icon: "Award", color: "pink", description: "Medical label materials and buyer-supplied symbols are reviewed by device scope, jurisdiction, substrate, exposure, retention target, printing system, and approved artwork. Final regulatory approval remains with the device manufacturer." },
];

export const BLOG_POSTS = [
  {
    slug: "bpa-free-thermal-paper-europe",
    title: "BPA-Free Thermal Paper in Europe: Complete Compliance Guide 2025",
    excerpt: "Everything distributors need to know about BPA-free thermal paper regulations in the EU, REACH compliance, and sourcing from certified manufacturers.",
    category: "Compliance",
    readTime: "8 min",
    date: "2025-03-15",
    tag: "SEO",
  },
  {
    slug: "what-is-thermal-paper",
    title: "What Is Thermal Paper? A Complete Technical Guide",
    excerpt: "Understanding thermal paper chemistry, types, applications, and how to choose the right thermal paper for your business needs.",
    category: "Education",
    readTime: "12 min",
    date: "2025-02-28",
    tag: "SEO",
  },
  {
    slug: "lottery-ticket-paper-specifications",
    title: "Lottery Ticket Paper Specifications: What You Need to Know",
    excerpt: "Technical specifications for lottery terminal thermal paper including sensitivity, density, and compliance requirements for gaming operators.",
    category: "Products",
    readTime: "6 min",
    date: "2025-02-10",
    tag: "SEO",
  },
  {
    slug: "casino-receipt-paper-guide",
    title: "Casino TITO Paper Guide: Choosing the Right Thermal Paper",
    excerpt: "Complete guide to TITO (Ticket-In Ticket-Out) thermal paper for casino slot machines, including specifications and supplier selection.",
    category: "Products",
    readTime: "7 min",
    date: "2025-01-20",
    tag: "SEO",
  },
  {
    slug: "freezer-label-adhesive-guide",
    title: "Freezer Label Adhesive Types: Which One Do You Need?",
    excerpt: "Comparing cold chain label adhesives for freezer applications, from -20°C to -40°C, with performance data and application recommendations.",
    category: "Products",
    readTime: "9 min",
    date: "2025-01-05",
  },
  {
    slug: "reach-compliance-thermal-paper",
    title: "REACH Compliance for Thermal Paper: EU 2025 Update",
    excerpt: "Latest REACH SVHC regulations affecting thermal paper in Europe, what distributors must verify, and how to ensure compliant sourcing.",
    category: "Compliance",
    readTime: "10 min",
    date: "2024-12-18",
    tag: "SEO",
  },
  {
    slug: "direct-vs-thermal-transfer",
    title: "Direct Thermal vs Thermal Transfer: Which Label Is Right for You?",
    excerpt: "Side-by-side comparison of direct thermal and thermal transfer labels covering durability, cost, applications, and printer compatibility.",
    category: "Education",
    readTime: "8 min",
    date: "2024-11-15",
    tag: "SEO",
  },
  {
    slug: "cannabis-label-requirements-usa",
    title: "Cannabis Label Requirements by US State: 2025 Guide",
    excerpt: "State-by-state breakdown of cannabis label requirements in the USA, including thermal label specifications and compliance tips for dispensaries.",
    category: "Compliance",
    readTime: "15 min",
    date: "2024-12-01",
    tag: "New",
  },
  {
    slug: "how-to-print-logo-on-thermal-paper-rolls",
    title: "How to Print Your Logo on Thermal Paper Rolls: Complete Guide",
    excerpt: "Step-by-step guide to custom logo printing on thermal paper rolls, including back print options, coupon printing, QR codes, and MOQ requirements for B2B buyers.",
    category: "Education",
    readTime: "10 min",
    date: "2026-04-10",
    tag: "New",
  },
  {
    slug: "amazon-fba-thermal-labels-guide",
    title: "Amazon FBA Thermal Label Sourcing Guide 2026",
    excerpt: "A sourcing guide to 4x6 FBA thermal labels, printer fit, barcode quality, facestock, adhesive, packing, samples, and bulk-order specifications.",
    category: "E-Commerce",
    readTime: "12 min",
    date: "2026-04-08",
    tag: "New",
  },
  {
    slug: "thermal-paper-printer-compatibility-guide",
    title: "Thermal Paper Printer Compatibility Guide",
    excerpt: "Match receipt rolls to POS printers, payment terminals, ATMs, and kiosks using model, width, OD, core ID, winding, sensing, and sample checks.",
    category: "Education",
    readTime: "9 min",
    date: "2026-07-20",
    tag: "New",
  },
  {
    slug: "thermal-paper-roll-sizes-guide",
    title: "Thermal Paper Roll Sizes Guide",
    excerpt: "Measure width, outer diameter, length, core ID, GSM, and winding before ordering POS, payment terminal, ATM, kiosk, or receipt printer rolls.",
    category: "Education",
    readTime: "8 min",
    date: "2026-04-05",
    tag: "New",
  },
];

export const NAV_ITEMS = [
  { label: "Home", href: "/" },
  {
    label: "Products",
    href: "/products",
    children: [
      {
        label: "Thermal Paper Rolls",
        href: "/products/thermal-paper-rolls",
        children: THERMAL_PAPER_ROLLS.map((p) => ({
          label: p.name,
          href: `/products/thermal-paper-rolls/${p.slug}`,
          tag: p.priority === "P1" ? "P1" : p.tag,
        })),
      },
      {
        label: "Thermal Labels",
        href: "/products/thermal-labels",
        children: THERMAL_LABELS.map((l) => ({
          label: l.name,
          href: `/products/thermal-labels/${l.slug}`,
          tag: l.priority === "P1" ? "P1" : l.tag,
        })),
      },
      { label: "Private Label Printing", href: "/oem-custom/private-label", tag: "P1" },
      { label: "Request Samples →", href: "/samples" },
    ],
  },
  {
    label: "Industries",
    href: "/industries",
    children: INDUSTRIES.map((i) => ({ label: i.name, href: `/industries/${i.slug}`, tag: i.tag })),
  },
  {
    label: "Factory",
    href: "/factory",
    children: [
      { label: "Factory Overview",     href: "/factory/overview",      tag: "P1" },
      { label: "Equipment & Machines", href: "/factory/equipment" },
      { label: "Production Capacity",  href: "/factory/capacity" },
      { label: "Quality Control",      href: "/factory/quality-control" },
      { label: "Virtual Factory Tour", href: "/factory/virtual-tour" },
    ],
  },
  {
    label: "Compliance",
    href: "/compliance",
    children: [
      { label: "Certificates & documents", href: "/compliance/certificates",   tag: "P1" },
      { label: "BPA-free grade review",    href: "/compliance/bpa-free",       tag: "SEO" },
      { label: "REACH & RoHS review",      href: "/compliance/reach-rohs",     tag: "SEO" },
      { label: "ISO 9001 review",          href: "/compliance/iso-9001" },
      { label: "FSC® paper review",        href: "/compliance/fsc-paper" },
      { label: "EU food-contact review",   href: "/compliance/eu-food-contact", tag: "New" },
      { label: "US food-contact review",   href: "/compliance/fda-us",         tag: "New" },
    ],
  },
  {
    label: "Resources",
    href: "/blog",
    children: [
      { label: "Blog",         href: "/blog" },
      { label: "Case Studies", href: "/case-studies", tag: "New" },
      { label: "FAQ",          href: "/faq",          tag: "SEO" },
    ],
  },
  {
    label: "About",
    href: "/about",
    children: [
      { label: "About Us", href: "/about" },
      { label: "Contact",  href: "/contact", tag: "P1" },
    ],
  },
  {
    label: "Markets",
    href: "/eu",
    children: [
      { label: "🇪🇺 Europe (EU)",        href: "/eu",            tag: "GEO" },
      { label: "🇩🇪 Germany",            href: "/eu/germany" },
      { label: "🇬🇧 United Kingdom",     href: "/eu/uk" },
      { label: "🇫🇷 France",             href: "/eu/france" },
      { label: "🇳🇱 Netherlands",        href: "/eu/netherlands" },
      { label: "🇵🇱 Poland",             href: "/eu/poland" },
      { label: "🇺🇸 United States (US)", href: "/us",            tag: "GEO" },
      { label: "🇨🇦 Canada (CA)",        href: "/ca",            tag: "GEO" },
    ],
  },
];
