// Zhixin Paper — Site Data
// Design: Modern Professional Blue

export const COMPANY = {
  name: "Zhixin Paper",
  tagline: "One-Stop Thermal Consumables Platform",
  description:
    "Leading manufacturer of thermal paper rolls and thermal labels, supplying distributors, importers, and factories across Europe, USA, and Canada.",
  email: "Sales@zxpapers.com",
  phone: "+86 153 3924 7872",
  whatsapp: "+86 187 9277 1927",
  address: "Building 15, Phase 1 Zone 2, Ronghao Industrial Park, Gaoling District, Xi'an, Shaanxi, China",
  founded: "2008",
  certifications: ["ISO 9001:2015", "BPA-Free", "REACH/RoHS", "FSC", "FDA Compliant"],
  stats: [
    { value: "500M+", label: "Rolls Produced Annually" },
    { value: "80+", label: "Countries Served" },
    { value: "15+", label: "Years Experience" },
    { value: "6", label: "Certifications" },
  ],
};

export const THERMAL_PAPER_ROLLS = [
  {
    slug: "standard-pos-rolls",
    name: "Standard POS Rolls",
    subtitle: "Cash Register & Receipt Paper",
    heroDesc: "The backbone of every retail operation. Our Standard POS Rolls deliver sharp, consistent receipts that never jam, fade, or disappoint — roll after roll, shift after shift.",
    description: "Trusted by retail chains across Europe and North America, our Standard POS Rolls are engineered for high-volume environments where reliability is non-negotiable. With a premium thermal coating that activates at precise temperatures, every receipt prints with crisp clarity from the first roll to the last. Available BPA-free to meet EU REACH requirements, and fully compatible with all major POS printer brands. Custom OEM printing and private label options available from 10,000 rolls.",
    keywords: "POS thermal paper rolls, cash register rolls, receipt paper wholesale, Epson compatible POS paper, 80x80mm thermal rolls, 57x40mm receipt rolls",
    sizes: ["57×38mm", "57×40mm", "57×50mm", "80×40mm", "80×50mm", "80×60mm", "80×80mm"],
    applications: ["Retail POS", "Supermarkets", "Restaurants"],
    features: [
      "Premium high-sensitivity coating for crisp, fade-resistant prints",
      "BPA-free formulation — fully REACH/EU compliant",
      "Universal compatibility with Epson, Star, Bixolon & all major brands",
      "Consistent roll diameter for uninterrupted high-volume operation",
    ],
    moq: "10,000 rolls",
    specifications: {
      "Grammage (GSM)": "48g / 55g / 60g",
      "Thickness": "60μm – 75μm",
      "Brightness": "≥ 92%",
      "Image Life": "3–5 Years (Standard Storage)",
      "Core Options": "Plastic / Cardboard (12mm, 17mm, 25mm)",
      "BPA Status": "BPA-Free Available (REACH Compliant)",
      "Print Speed": "Up to 250mm/sec",
      "Min. Order Qty": "10,000 rolls",
      "Lead Time": "10–15 Business Days",
      "Certification": "ISO 9001:2015",
    },
    priority: "P1",
  },
  {
    slug: "credit-card-terminal-rolls",
    name: "Credit Card Terminal Rolls",
    subtitle: "Payment Terminal & EDC Receipt Paper",
    heroDesc: "Compact direct thermal receipt rolls qualified by terminal model, width, OD or length, core ID, winding direction, paper grade, and pack plan.",
    description: "Credit card terminal paper rolls for payment-terminal distributors, merchant service providers, banks, acquiring channels, and multi-model device fleets. Common buyer names include payment terminal rolls, EDC rolls, EFTPOS rolls, and credit card machine paper. Compatibility is confirmed against the exact terminal and approved sample rather than brand name alone.",
    keywords: "credit card terminal paper rolls, payment terminal rolls, credit card machine paper, EDC paper rolls, EFTPOS rolls, 57mm thermal paper rolls, 2 1/4 inch receipt paper",
    sizes: ["57×38mm", "57×40mm", "57×50mm", "2 1/4 in × 50 ft", "2 1/4 in × 85 ft", "Custom by model"],
    applications: ["Countertop payment terminals", "Mobile POS terminals", "EDC machines", "EFTPOS fleets"],
    features: [
      "Model-based fit check before bulk approval",
      "Width, OD or length, core, and winding locked by SKU",
      "BPA-free, BPS-free, or phenol-free routes by selected grade",
      "Plain, reverse-print, and private-label packing options",
    ],
    moq: "Confirmed by size, packing, and annual volume",
    specifications: {
      "Common Width Family": "57mm / 2 1/4 inch",
      "Length or OD": "Confirmed by terminal compartment and buyer format",
      "Core Options": "Coreless or specified core ID, subject to model",
      "Winding Direction": "Confirmed from current roll or terminal path",
      "Paper Grade": "Matched by sensitivity, image-life, and document need",
      "End Mark / Black Mark": "Available when required by the mechanism",
      "Printing": "Plain or controlled reverse-side print",
      "Packing": "Units per box, carton count, and SKU marks confirmed at RFQ",
    },
    tag: "SEO",
  },
  {
    slug: "atm-banking-rolls",
    name: "ATM & Bank Receipt Rolls",
    subtitle: "Archival-Grade Bank Receipt & ATM Paper",
    heroDesc: "Every ATM transaction generates a receipt that must be flawless, readable, and legally archivable. Our ATM & Bank Receipt Rolls are engineered to the exacting standards of the global banking industry — 7-year archival life, anti-static coating, and BPA-free as standard.",
    description: "Banking and financial terminals demand the highest standards in thermal paper. Our ATM & Bank Receipt Rolls are manufactured with an archival-grade thermal coating that preserves transaction records for up to 7 years, meeting regulatory requirements under EU PSD2, US Regulation E, and international banking standards. The precision anti-static surface treatment eliminates static-induced paper jams in sensitive ATM mechanisms, reducing maintenance calls and downtime. High-speed compatible at up to 300mm/sec, these rolls perform flawlessly in Diebold Nixdorf, NCR, Wincor, Hyosung, and all major ATM platforms. BPA-free certified as standard — no special order required. Available in standard ATM widths (57mm, 80mm, 82.5mm) and custom widths for specialized terminals. Optional back-print available for regulatory disclosures, terms & conditions, or promotional messaging.",
    keywords: "ATM paper rolls, bank receipt paper, ATM thermal paper wholesale, banking receipt rolls, 7-year archival thermal paper, Diebold Nixdorf paper, NCR ATM paper, BPA free bank receipt paper, back print thermal paper",
    sizes: ["57×40mm", "57×50mm", "80×60mm", "80×70mm", "80×80mm", "82.5×80mm", "Custom"],
    applications: ["ATM machines", "Bank teller terminals", "Financial kiosks", "Currency exchange terminals", "Investment trading terminals"],
    features: [
      "7-year archival life — meets EU PSD2 and US Regulation E record-keeping requirements",
      "Anti-static coating eliminates paper jams in sensitive ATM mechanisms",
      "High-speed compatible up to 300mm/sec — no slowdown at peak transaction times",
      "BPA-free certified as standard — no surcharge, no special order required",
      "Compatible with Diebold Nixdorf, NCR, Wincor, Hyosung, and all major ATM platforms",
      "Optional back-print for regulatory disclosures, T&Cs, or promotional messaging",
    ],
    moq: "5,000 rolls",
    specifications: {
      "Grammage (GSM)": "55g / 65g / 70g",
      "Thickness": "70μm – 85μm",
      "Brightness": "≥ 92%",
      "Image Life": "7 Years (Archival Grade)",
      "Anti-Static Coating": "Yes (standard)",
      "Back-Print Option": "Available (black / blue ink)",
      "Core Options": "Plastic (17mm, 25mm)",
      "BPA Status": "BPA-Free (standard, no surcharge)",
      "Print Speed": "Up to 300mm/sec",
      "Compatible Platforms": "Diebold Nixdorf, NCR, Wincor, Hyosung",
      "Min. Order Qty": "5,000 rolls",
      "Lead Time": "10–15 Business Days",
      "Certification": "ISO 9001:2015 / REACH",
    },
    priority: "P1",
  },
  {
    slug: "lottery-gaming-rolls",
    name: "Lottery & Gaming Rolls",
    subtitle: "Lottery Ticket Thermal Paper",
    heroDesc: "Precision-engineered for the gaming industry. Our Lottery & Gaming Rolls deliver the reliability, security, and print quality that lottery operators and gaming regulators demand.",
    description: "Lottery terminals operate 24/7 under demanding conditions — and your ticket paper must keep pace. Our Lottery & Gaming Rolls feature high-density thermal coating that produces razor-sharp barcodes scannable at any angle, with optional security features including UV-reactive inks and void patterns. Fade-resistant for the full ticket validity period. Supplied to national lottery operators and gaming machine manufacturers across Europe.",
    keywords: "lottery ticket thermal paper, gaming ticket paper supplier, lottery terminal paper rolls, gaming paper wholesale",
    sizes: ["57×40mm", "80×50mm", "80×80mm", "80×70mm", "Custom widths"],
    applications: ["Lottery terminals", "Gaming machines", "Betting shops"],
    features: [
      "High-density coating for razor-sharp, scannable barcodes",
      "Fade-resistant — maintains print integrity for full ticket validity period",
      "Optional UV-reactive security features and void patterns",
      "Tested and approved for major European lottery terminal brands",
    ],
    moq: "20,000 rolls",
    specifications: {
      "Grammage (GSM)": "55g / 60g",
      "Thickness": "65μm – 80μm",
      "Coating Density": "High-density (barcode optimised)",
      "Image Life": "5 Years (Full Ticket Validity)",
      "Security Features": "UV-reactive ink, Void patterns (optional)",
      "Core Options": "Plastic / Cardboard (17mm, 25mm)",
      "Print Speed": "Up to 250mm/sec",
      "Min. Order Qty": "20,000 rolls",
      "Lead Time": "15–20 Business Days",
      "Certification": "ISO 9001:2015",
    },
    tag: "SEO",
  },
  {
    slug: "casino-tito-rolls",
    name: "Casino TITO Rolls",
    subtitle: "Ticket-In Ticket-Out Paper",
    heroDesc: "The casino floor never sleeps — and neither does your TITO system. Our Casino TITO Rolls are built for continuous, high-speed operation in the world's most demanding gaming environments.",
    description: "TITO (Ticket-In Ticket-Out) systems require paper that performs flawlessly at high speeds, in variable humidity, and across millions of print cycles. Our Casino TITO Rolls feature a specially formulated thermal coating optimized for barcode density and scan reliability, with a 5-year shelf life and humidity-resistant packaging. Fully compatible with IGT, Aristocrat, Konami, and all major slot machine platforms.",
    keywords: "casino TITO paper, slot machine receipt paper, ticket-in ticket-out paper, IGT compatible TITO rolls, casino thermal paper wholesale",
    sizes: ["80×70mm", "80×80mm"],
    applications: ["Slot machines", "Casino terminals", "Gaming kiosks"],
    features: [
      "Optimized for maximum barcode density and 360° scan reliability",
      "High-speed compatible — tested up to 250mm/sec",
      "5-year shelf life with humidity-resistant packaging",
      "Compatible with IGT, Aristocrat, Konami, and all major platforms",
    ],
    moq: "10,000 rolls",
    specifications: {
      "Grammage (GSM)": "55g / 60g",
      "Thickness": "65μm – 80μm",
      "Coating": "High-density barcode optimised",
      "Image Life": "5 Years",
      "Humidity Resistance": "Yes (special packaging)",
      "Core Options": "Plastic (17mm, 25mm)",
      "Print Speed": "Up to 250mm/sec",
      "Min. Order Qty": "10,000 rolls",
      "Lead Time": "10–15 Business Days",
      "Certification": "ISO 9001:2015",
    },
    tag: "SEO",
  },
  {
    slug: "parking-ticketing-rolls",
    name: "Parking & Ticketing Rolls",
    subtitle: "Parking Ticket Paper",
    heroDesc: "From underground car parks to open-air toll plazas, our Parking & Ticketing Rolls withstand the elements while delivering clear, scannable tickets every time.",
    description: "Outdoor ticketing environments expose paper to UV radiation, moisture, and extreme temperatures. Our Parking & Ticketing Rolls are engineered with a UV-stable, weather-resistant coating that keeps barcodes scannable and text legible even after prolonged outdoor exposure. High-contrast printing ensures readability in all lighting conditions. Trusted by parking operators and transit authorities across Europe.",
    keywords: "parking ticket paper, thermal ticket rolls",
    sizes: ["57×38mm", "57×40mm", "80×50mm", "80×60mm", "Custom"],
    applications: ["Parking meters", "Toll booths", "Transit ticketing"],
    features: [
      "UV-stable coating — resists fading in direct sunlight",
      "Weather-resistant surface withstands rain, humidity, and temperature swings",
      "High-contrast printing for barcode readability in all conditions",
      "Custom sizes available for any parking or transit system",
    ],
    moq: "15,000 rolls",
    specifications: {
      "Grammage (GSM)": "55g / 60g",
      "Thickness": "65μm – 80μm",
      "UV Resistance": "Yes (UV-stable coating)",
      "Weather Resistance": "Yes (moisture-resistant)",
      "Image Life": "3–5 Years (Outdoor Conditions)",
      "Core Options": "Plastic / Cardboard (17mm, 25mm)",
      "Print Speed": "Up to 200mm/sec",
      "Min. Order Qty": "10,000 rolls",
      "Lead Time": "10–15 Business Days",
      "Certification": "ISO 9001:2015",
    },
    tag: "SEO",
  },
  {
    slug: "medical-rolls",
    name: "Medical Paper Rolls",
    subtitle: "Patient Records & Medical Receipts",
    heroDesc: "In healthcare, every printed record matters. Our Medical Paper Rolls are BPA-free certified, long-life, and compliant with the strictest EU and US medical standards.",
    description: "Healthcare environments demand thermal paper that is safe for patients, durable for records, and compliant with regulatory requirements. Our Medical Paper Rolls are manufactured BPA-free as standard, with a long archival coating that preserves patient data for up to 10 years. Chemical-resistant surface withstands common hospital disinfectants. Suitable for patient wristband printers, pharmacy POS systems, and medical device outputs.",
    keywords: "medical thermal paper, patient receipt paper, BPA free medical paper, FDA compliant medical thermal paper, hospital receipt rolls",
    sizes: ["57×38mm", "57×40mm", "57×50mm", "80×50mm", "80×80mm"],
    applications: ["Hospital kiosks", "Pharmacy POS", "Medical devices"],
    features: [
      "BPA-free certified as standard — no special order required",
      "10-year archival life for long-term patient record retention",
      "Chemical-resistant surface withstands hospital disinfectants",
      "Compliant with EU Medical Device Regulation and US FDA standards",
    ],
    moq: "5,000 rolls",
    specifications: {
      "Grammage (GSM)": "55g / 60g",
      "Thickness": "65μm – 80μm",
      "BPA Status": "BPA-Free (Standard, No Surcharge)",
      "Image Life": "10 Years (Archival Grade)",
      "Chemical Resistance": "Yes (hospital disinfectants)",
      "Core Options": "Plastic / Cardboard (12mm, 17mm, 25mm)",
      "Print Speed": "Up to 200mm/sec",
      "Min. Order Qty": "5,000 rolls",
      "Lead Time": "10–15 Business Days",
      "Certification": "ISO 9001:2015 / FDA 21 CFR",
    },
  },
  {
    slug: "transport-ticket-rolls",
    name: "Transport Ticket Rolls",
    subtitle: "Bus, Rail & Transit Tickets",
    heroDesc: "Millions of journeys begin with a printed ticket. Our Transport Ticket Rolls deliver the durability and scan reliability that public transit networks depend on.",
    description: "Public transport ticketing demands paper that survives the journey — from the printer to the validator to the passenger's pocket. Our Transport Ticket Rolls feature a durable thermal coating that maintains barcode integrity through handling, folding, and exposure to light. Compatible with all major transit ticket printers including Scheidt & Bachmann, Parkeon, and Cubic. Custom sizes and security features available for any transit system.",
    keywords: "bus ticket paper, rail ticket paper rolls",
    sizes: ["57×38mm", "57×40mm", "80×50mm", "80×60mm", "Custom"],
    applications: ["Bus terminals", "Train stations", "Ferry terminals"],
    features: [
      "Durable coating maintains barcode integrity through heavy handling",
      "High-speed compatible for rapid ticket issuance at peak times",
      "Compatible with Scheidt & Bachmann, Parkeon, Cubic, and more",
      "Custom security features available for anti-fraud applications",
    ],
    moq: "20,000 rolls",
    specifications: {
      "Grammage (GSM)": "55g / 60g",
      "Thickness": "65μm – 80μm",
      "Coating": "Durable, high-contrast",
      "Image Life": "3–5 Years",
      "Core Options": "Plastic / Cardboard (17mm, 25mm)",
      "Print Speed": "Up to 250mm/sec",
      "Min. Order Qty": "20,000 rolls",
      "Lead Time": "10–15 Business Days",
      "Certification": "ISO 9001:2015",
    },
    tag: "New",
  },
  {
    slug: "kiosk-vending-rolls",
    name: "Kiosk & Vending Rolls",
    subtitle: "Kiosk Receipt & Vending Machine Paper",
    heroDesc: "Self-service never stops. Our Kiosk & Vending Rolls are engineered for unattended operation — reliable across extreme temperatures, compact spaces, and millions of print cycles.",
    description: "Unattended kiosks and vending machines demand paper that performs without human intervention. Our Kiosk & Vending Rolls are formulated for a wide operating temperature range (-10°C to +60°C), making them suitable for outdoor kiosks, refrigerated vending machines, and high-heat environments. Compact core sizes fit the tightest printer compartments, while our high-reliability coating minimizes paper jams and service calls.",
    keywords: "kiosk receipt paper, vending machine rolls",
    sizes: ["57×38mm", "57×40mm", "57×50mm", "80×50mm", "80×80mm"],
    applications: ["Self-service kiosks", "Vending machines", "Information terminals"],
    features: [
      "Wide operating range: -10°C to +60°C for any environment",
      "High-reliability coating minimizes jams in unattended machines",
      "Compact core sizes fit the tightest printer compartments",
      "Long roll lengths reduce service frequency and operational costs",
    ],
    moq: "10,000 rolls",
    specifications: {
      "Grammage (GSM)": "48g / 55g / 60g",
      "Thickness": "60μm – 75μm",
      "Operating Temp.": "-10°C to +60°C",
      "Image Life": "3–5 Years",
      "Core Options": "Plastic / Cardboard (12mm, 17mm, 25mm)",
      "Print Speed": "Up to 200mm/sec",
      "Min. Order Qty": "10,000 rolls",
      "Lead Time": "10–15 Business Days",
      "Certification": "ISO 9001:2015",
    },
    tag: "New",
  },
  {
    slug: "custom-printed-rolls",
    name: "Custom Printed Rolls",
    subtitle: "OEM & Private Label Thermal Paper",
    heroDesc: "Your brand on every receipt. Our Custom Printed Rolls turn a functional consumable into a powerful marketing touchpoint — with no compromise on print quality or compliance.",
    description: "Transform your thermal paper into a brand asset. Our Custom Printed Rolls service offers full-color pre-printing on any standard or custom roll size, with options including logo printing, promotional messaging, QR codes, and custom packaging. Front-side printing adds your logo, store address, and website URL to every receipt header. Back-side printing turns the reverse of the roll into a full-color advertising canvas — ideal for promotional coupons, loyalty program details, QR codes linking to online stores, and seasonal offers. Back-print receipts achieve 3-5x higher coupon redemption rates than traditional paper coupons. All custom orders are manufactured to the same ISO 9001:2015 standards as our standard range, with BPA-free and REACH-compliant options available. Artwork accepted as AI, EPS, or PDF vector files; Pantone spot color matching available. Minimum order from 10,000 rolls (back-print) or 5,000 rolls (front-print) with 20-30 day lead time from artwork approval.",
    keywords: "custom printed thermal rolls, OEM thermal paper, private label receipt paper, branded thermal rolls, custom logo receipt paper, back print thermal paper, receipt paper with logo, promotional receipt paper, QR code receipt paper, custom thermal paper wholesale",
    sizes: ["57×38mm", "57×40mm", "57×50mm", "80×40mm", "80×50mm", "80×60mm", "80×80mm", "Custom widths"],
    applications: ["Brand promotion on receipts", "Promotional coupons & loyalty programs", "QR code marketing", "Private label & OEM", "ATM back-print disclosures"],
    features: [
      "Front-print: logo, address, website URL on every receipt header",
      "Back-print: full-color coupons, QR codes, loyalty details — 3-5x higher redemption than paper coupons",
      "Pantone spot color matching for precise brand color reproduction",
      "ISO 9001:2015 quality on every custom order; BPA-free and REACH-compliant",
      "Artwork accepted as AI, EPS, or PDF — free print template provided",
      "Free pre-production physical sample before bulk production",
    ],
    moq: "5,000 rolls (front-print) / 10,000 rolls (back-print)",
    specifications: {
      "Grammage (GSM)": "48g / 55g / 60g / 65g",
      "Print Method": "Flexographic (water-based inks)",
      "Print Side": "Front-side / Back-side / Both",
      "Colors": "1-4 colors (CMYK); Pantone spot color available",
      "Artwork Format": "AI / EPS / PDF (vector)",
      "QR Code Min. Size": "20mm × 20mm (reliable scanning)",
      "Packaging": "Custom branded packaging available",
      "BPA Status": "BPA-Free Available",
      "Core Options": "Plastic / Cardboard (12mm, 17mm, 25mm)",
      "Min. Order Qty": "5,000 rolls (front-print) / 10,000 rolls (back-print)",
      "Lead Time": "20–30 Business Days from Artwork Approval",
      "Certification": "ISO 9001:2015 / REACH / RoHS",
    },
  },
  {
    slug: "back-print-thermal-rolls",
    name: "Back Print Thermal Rolls",
    subtitle: "Pre-Printed Reverse Side Thermal Paper",
    heroDesc: "Turn the back of every receipt into a revenue opportunity. Our Back Print Thermal Rolls let you pre-print coupons, legal disclosures, loyalty program details, or brand messaging on the reverse side — at no extra print cost to your customer.",
    description: "Back print thermal paper features a pre-printed reverse side combined with a standard thermal-sensitive front face. This dual-sided format is widely used in banking (regulatory disclosures, T&Cs), retail (coupons, loyalty rewards), hospitality (menu promotions, survey QR codes), and healthcare (patient rights, medication instructions). The back print is applied during manufacturing using high-resolution flexographic or offset printing, ensuring consistent quality across every roll. Front-face thermal performance is unaffected — same brightness, same sensitivity, same archival life as our standard rolls. Available in any standard or custom width, with MOQ from 30,000 rolls. Full-color back print available; Pantone color matching on request.",
    keywords: "back print thermal paper, pre-printed thermal rolls, thermal paper back printing, reverse print receipt paper, coupon thermal paper, regulatory disclosure receipt paper, back printed ATM paper",
    sizes: ["57×38mm", "57×40mm", "57×50mm", "80×50mm", "80×60mm", "80×70mm", "80×80mm", "82.5×80mm", "Custom"],
    applications: ["ATM & banking receipts", "Retail POS coupons", "Restaurant & hospitality", "Healthcare patient records", "Parking & transit tickets"],
    features: [
      "Pre-printed reverse side — coupons, disclosures, QR codes, or brand messaging",
      "Front thermal performance unaffected — same sensitivity and archival life",
      "Full-color back print with Pantone color matching available",
      "Ideal for regulatory compliance: banking T&Cs, healthcare patient rights",
      "Drives repeat business: loyalty rewards, promotional coupons, survey links",
      "Available in all standard widths and custom sizes from 30,000 rolls",
    ],
    moq: "30,000 rolls",
    specifications: {
      "Grammage (GSM)": "55g / 60g / 65g",
      "Thickness": "65μm – 80μm",
      "Brightness (Front)": "≥ 92%",
      "Image Life (Front)": "3–7 Years (coating dependent)",
      "Back Print Method": "Flexographic / Offset printing",
      "Back Print Colors": "1–4 colors (full color available)",
      "Pantone Matching": "Available on request",
      "BPA Status": "BPA-Free Available (REACH Compliant)",
      "Core Options": "Plastic / Cardboard (12mm, 17mm, 25mm)",
      "Min. Order Qty": "30,000 rolls",
      "Lead Time": "20–25 Business Days",
      "Certification": "ISO 9001:2015 / REACH / RoHS",
    },
    tag: "New",
  },
];

export const THERMAL_LABELS = [
  {
    slug: "direct-thermal-labels",
    name: "Direct Thermal Labels",
    subtitle: "No Ribbon Required — Shipping & Logistics Grade",
    heroDesc: "The smart choice for high-volume shipping and e-commerce fulfillment. No ribbon, no hassle — just fast, clean, cost-effective labels that keep your operation moving at Amazon FBA speed.",
    description: "Direct thermal labels are the industry standard for shipping, e-commerce fulfillment, and warehouse operations. Our labels are pre-validated on Zebra ZD420, ZD620, and GX430t printers — the models used at Amazon fulfillment centers and major 3PL facilities — ensuring 100% scan-through-rate at high-speed sortation conveyors. Barcode image life guaranteed 24 months, meeting Amazon FBA label retention requirements. GS1-128 and GS1 DataMatrix barcode formats supported for SSCC pallet labels and GS1 compliance. Compatible with DHL, Hermes, DPD, GLS, UPS, and FedEx carrier label formats for European and North American last-mile delivery. Available in roll and fanfold formats; permanent and removable adhesive options.",
    keywords: "direct thermal labels bulk, DT labels supplier, shipping labels 4x6, Zebra compatible labels, 100x150mm thermal labels wholesale, Amazon FBA labels, Zebra GX430t labels, GS1 barcode labels, DHL shipping labels, ecommerce fulfillment labels, 3PL thermal labels Europe",
    sizes: ["55×25mm", "60×40mm", "75×50mm", "100×50mm", "100×150mm", "4×6 inch", "Custom"],
    applications: ["Amazon FBA fulfillment", "E-commerce shipping", "3PL warehouse operations", "Retail pricing", "Logistics & distribution"],
    features: [
      "Pre-validated on Zebra GX430t — Amazon fulfillment center standard printer",
      "Barcode image life guaranteed 24 months — meets Amazon FBA label requirements",
      "GS1-128 and SSCC pallet label formats supported for supply chain compliance",
      "Compatible with DHL, Hermes, DPD, GLS, UPS, FedEx carrier label formats",
      "No ribbon required — eliminates consumable cost and changeover time",
      "Available in roll and fanfold formats for any workflow configuration",
    ],
    moq: "50,000 labels",
    specifications: {
      "Facestock": "Thermal-sensitive paper (white / yellow)",
      "Adhesive": "Permanent acrylic (standard) / Removable (optional)",
      "Liner": "Glassine / PE",
      "Label Format": "Roll / Fanfold",
      "Print Method": "Direct Thermal (no ribbon required)",
      "Print Speed": "Up to 300mm/sec",
      "Barcode Standards": "GS1-128, GS1 DataMatrix, SSCC, Code 128, QR",
      "Image Life": "24 Months (Amazon FBA compliant)",
      "Printer Compatibility": "Zebra ZD420/ZD620/GX430t, Honeywell, SATO, Dymo",
      "Carrier Compatibility": "DHL, Hermes, DPD, GLS, UPS, FedEx, Amazon",
      "Min. Order Qty": "50,000 labels",
      "Lead Time": "10–15 Business Days",
      "Certification": "ISO 9001:2015 / REACH",
    },
    priority: "P1",
  },
  {
    slug: "thermal-transfer-labels",
    name: "Thermal Transfer Labels",
    subtitle: "Durable Long-Life Labels",
    heroDesc: "When labels need to last years, not days. Our Thermal Transfer Labels are engineered for industrial durability — surviving chemicals, UV exposure, and extreme conditions.",
    description: "Some applications demand labels that outlast the products they identify. Our Thermal Transfer Labels use a ribbon-based printing process that produces images with exceptional durability, resistant to chemicals, UV radiation, and abrasion. Ideal for industrial asset tracking, outdoor equipment, and chemical containers where direct thermal labels would degrade. Available on paper, polyester, and polypropylene facestocks with a range of adhesive options.",
    keywords: "thermal transfer labels, TT labels manufacturer",
    sizes: ["55×25mm", "60×40mm", "75×50mm", "100×50mm", "100×150mm", "Custom"],
    applications: ["Industrial assets", "Outdoor use", "Chemical exposure"],
    features: [
      "Ribbon-based printing for exceptional chemical and UV resistance",
      "Available on paper, polyester, and polypropylene facestocks",
      "Extreme durability — tested to 5+ years outdoor exposure",
      "Multiple adhesive options including high-tack and low-temperature",
    ],
    moq: "30,000 labels",
    specifications: {
      "Facestock": "Paper / Polyester (PET) / Polypropylene (PP)",
      "Adhesive": "Permanent / High-tack / Low-temperature",
      "Liner": "Glassine / PE / PET",
      "Label Format": "Roll",
      "Print Method": "Thermal Transfer (ribbon required)",
      "Outdoor Durability": "5+ Years",
      "Min. Order Qty": "30,000 labels",
      "Lead Time": "10–15 Business Days",
      "Certification": "ISO 9001:2015",
    },
  },
  {
    slug: "high-temperature-labels",
    name: "High Temperature Labels",
    subtitle: "Heat Resistant up to 150°C",
    heroDesc: "Labels that stay put when the heat is on. Engineered for automotive, electronics, and industrial manufacturing environments where standard labels simply fail.",
    description: "Standard labels peel, bubble, and fail in high-temperature environments. Our High Temperature Labels are specifically engineered to maintain adhesion and legibility at temperatures up to 150°C, making them essential for automotive parts tracking, electronics PCB identification, and industrial process labeling. The specialized acrylic adhesive maintains bond strength through thermal cycling, and the polyimide or aluminum foil facestock options provide additional protection in extreme environments.",
    keywords: "high temp labels, heat resistant labels 150C",
    sizes: ["55×25mm", "60×40mm", "75×50mm", "100×50mm", "Custom"],
    applications: ["Automotive parts", "Electronics manufacturing", "Industrial processes"],
    features: [
      "Rated to 150°C continuous — survives reflow soldering and paint ovens",
      "Specialized acrylic adhesive maintains bond through thermal cycling",
      "Polyimide and aluminum foil facestock options for extreme environments",
      "No delamination, bubbling, or adhesive failure under heat stress",
    ],
    moq: "20,000 labels",
    specifications: {
      "Facestock": "Polyimide (Kapton) / Aluminum Foil",
      "Adhesive": "Specialized acrylic (high-temp)",
      "Max. Temperature": "150°C Continuous",
      "Thermal Cycling": "Yes (no delamination)",
      "Label Format": "Roll",
      "Min. Order Qty": "20,000 labels",
      "Lead Time": "15–20 Business Days",
      "Certification": "ISO 9001:2015",
    },
    tag: "SEO",
  },
  {
    slug: "freezer-cold-chain-labels",
    name: "Freezer & Cold Chain Labels",
    subtitle: "Cryo & Freeze Labels",
    heroDesc: "From the production line to -40°C frozen storage, our Cold Chain Labels maintain adhesion, legibility, and compliance at every stage of the cold chain.",
    description: "Cold chain integrity depends on labels that perform in freezing conditions. Our Freezer & Cold Chain Labels use a specially formulated low-temperature adhesive that bonds securely to frozen surfaces and maintains adhesion through freeze-thaw cycles. The moisture-resistant facestock prevents condensation damage, while the high-contrast thermal coating ensures barcode readability even after prolonged cold storage. Compliant with EU food contact regulations and FDA requirements for pharmaceutical cold chain.",
    keywords: "freezer labels, cryo labels, cold chain adhesive labels, -40C freezer labels, FDA cold chain labels, frozen food labels wholesale",
    sizes: ["55×25mm", "60×40mm", "75×50mm", "100×50mm", "Custom"],
    applications: ["Frozen food", "Pharmaceutical cold chain", "Lab specimens"],
    features: [
      "Bonds securely to frozen surfaces down to -40°C",
      "Maintains adhesion through repeated freeze-thaw cycles",
      "Moisture-resistant facestock prevents condensation damage",
      "EU food contact and FDA pharmaceutical cold chain compliant",
    ],
    moq: "25,000 labels",
    specifications: {
      "Facestock": "Moisture-resistant paper / PP",
      "Adhesive": "Low-temperature acrylic",
      "Min. Temperature": "-40°C",
      "Freeze-Thaw Cycles": "Tested (no adhesion loss)",
      "Label Format": "Roll",
      "Compliance": "EU Food Contact / FDA Pharma Cold Chain",
      "Min. Order Qty": "25,000 labels",
      "Lead Time": "15–20 Business Days",
      "Certification": "ISO 9001:2015",
    },
    tag: "SEO",
  },
  {
    slug: "removable-labels",
    name: "Removable Labels",
    subtitle: "Clean Peel Labels",
    heroDesc: "Stick when you need them. Peel when you don't. Our Removable Labels leave no residue, no damage, and no trace — just clean, professional results every time.",
    description: "Removable labels demand a precise balance: strong enough to stay in place during use, gentle enough to remove without damage. Our Removable Labels use a specially engineered low-tack adhesive that provides reliable adhesion to a wide range of surfaces while peeling cleanly without residue. Ideal for retail price tags, temporary product identification, and reusable packaging. Available on paper and synthetic facestocks for indoor and outdoor applications.",
    keywords: "removable thermal labels, clean peel labels",
    sizes: ["55×25mm", "60×40mm", "75×50mm", "100×50mm", "Custom"],
    applications: ["Retail price tags", "Temporary marking", "Reusable packaging"],
    features: [
      "Clean removal with zero adhesive residue on all common surfaces",
      "Repositionable — reapply up to 3 times without loss of adhesion",
      "Available on paper and synthetic facestocks for any application",
      "Tested on glass, plastic, metal, and coated cardboard",
    ],
    moq: "30,000 labels",
    specifications: {
      "Facestock": "Thermal-sensitive paper (white)",
      "Adhesive": "Removable acrylic (clean peel)",
      "Liner": "Glassine",
      "Label Format": "Roll / Fanfold",
      "Print Method": "Direct Thermal",
      "Min. Order Qty": "30,000 labels",
      "Lead Time": "10–15 Business Days",
      "Certification": "ISO 9001:2015",
    },
  },
  {
    slug: "synthetic-paper-labels",
    name: "Synthetic PP Labels",
    subtitle: "Waterproof & Tear-Resistant",
    heroDesc: "Paper labels fail in wet, outdoor, and harsh environments. Our Synthetic PP Labels are built to survive conditions that would destroy ordinary labels.",
    description: "When your application demands a label that paper simply cannot handle, our Synthetic PP Labels deliver. Made from 100% polypropylene facestock, these labels are completely waterproof, tear-resistant, and UV-stable — making them ideal for outdoor equipment, chemical containers, marine applications, and any environment where moisture or physical stress is a factor. The clear and white PP options support both direct thermal and thermal transfer printing.",
    keywords: "synthetic paper labels, waterproof PP labels",
    sizes: ["55×25mm", "60×40mm", "75×50mm", "100×50mm", "100×150mm", "Custom"],
    applications: ["Outdoor assets", "Chemical containers", "Marine use"],
    features: [
      "100% waterproof — fully submersible without print degradation",
      "Tear-resistant polypropylene facestock withstands physical stress",
      "UV-stable for outdoor use without fading or delamination",
      "Available in clear and white for direct thermal and thermal transfer",
    ],
    moq: "20,000 labels",
    specifications: {
      "Facestock": "Polypropylene (PP) synthetic",
      "Adhesive": "Permanent acrylic",
      "Liner": "PE / PET",
      "Tear Resistance": "Yes (waterproof, tear-proof)",
      "Label Format": "Roll",
      "Min. Order Qty": "20,000 labels",
      "Lead Time": "15–20 Business Days",
      "Certification": "ISO 9001:2015",
    },
  },
  {
    slug: "tamper-evident-labels",
    name: "Tamper-Evident Labels",
    subtitle: "Security & Void Labels",
    heroDesc: "Protect your products, your brand, and your customers. Our Tamper-Evident Labels make unauthorised access immediately visible — and impossible to conceal.",
    description: "Product security starts with the label. Our Tamper-Evident Labels are engineered to provide clear, undeniable evidence of any tampering attempt. When removed, the label leaves a permanent 'VOID' pattern on the surface, while the facestock itself destructs to prevent reapplication. Available with custom security print, sequential numbering, and QR codes for product authentication. Used by pharmaceutical companies, electronics manufacturers, and high-value goods distributors worldwide.",
    keywords: "tamper evident labels wholesale, security labels",
    sizes: ["55×25mm", "60×40mm", "75×50mm", "100×50mm", "Custom"],
    applications: ["Electronics", "Pharmaceuticals", "High-value goods"],
    features: [
      "Permanent 'VOID' pattern revealed on any removal attempt",
      "Destructible facestock prevents reapplication after tampering",
      "Custom security print, sequential numbering, and QR code options",
      "Meets pharmaceutical and electronics industry security standards",
    ],
    moq: "20,000 labels",
    specifications: {
      "Facestock": "Destructible vinyl / VOID material",
      "Adhesive": "Permanent (tamper-evident)",
      "Tamper Feature": "VOID pattern on removal",
      "Label Format": "Roll",
      "Min. Order Qty": "20,000 labels",
      "Lead Time": "15–20 Business Days",
      "Certification": "ISO 9001:2015",
    },
    tag: "New",
  },
  {
    slug: "chemical-resistant-labels",
    name: "Chemical Resistant Labels",
    subtitle: "Chemical & Solvent Resistant",
    heroDesc: "Laboratories, chemical plants, and industrial facilities demand labels that survive exposure to solvents, acids, and autoclave sterilization. Ours do.",
    description: "Chemical environments are hostile to ordinary labels. Our Chemical Resistant Labels are engineered to maintain adhesion, legibility, and structural integrity when exposed to common laboratory chemicals, industrial solvents, and cleaning agents. The polyester facestock and solvent-resistant overcoat protect against xylene, acetone, methanol, and bleach, while the autoclave-compatible adhesive withstands sterilization cycles up to 134°C. Compliant with GHS/CLP labeling requirements for chemical storage.",
    keywords: "chemical resistant labels, solvent resistant labels",
    sizes: ["55×25mm", "60×40mm", "75×50mm", "100×50mm", "Custom"],
    applications: ["Lab specimens", "Chemical storage", "Industrial fluids"],
    features: [
      "Resistant to xylene, acetone, methanol, bleach, and common solvents",
      "Autoclave-compatible adhesive — survives sterilization at 134°C",
      "Polyester facestock maintains structural integrity under chemical exposure",
      "Compliant with GHS/CLP chemical labeling requirements",
    ],
    moq: "20,000 labels",
    specifications: {
      "Facestock": "Polyester (PET)",
      "Adhesive": "Autoclave-compatible acrylic",
      "Chemical Resistance": "Xylene, acetone, methanol, bleach",
      "Autoclave": "Up to 134°C sterilization",
      "Label Format": "Roll",
      "Compliance": "GHS / CLP",
      "Min. Order Qty": "20,000 labels",
      "Lead Time": "15–20 Business Days",
      "Certification": "ISO 9001:2015",
    },
    tag: "New",
  },
  {
    slug: "wristband-labels",
    name: "Wristband Labels",
    subtitle: "Hospital & Event Wristbands",
    heroDesc: "Patient safety and event security depend on wristbands that stay on, stay readable, and stay comfortable. Our Wristband Labels deliver all three.",
    description: "From hospital patient identification to festival access control, our Wristband Labels are designed for the most demanding wear applications. The skin-safe, hypoallergenic adhesive is tested to remain comfortable for extended wear periods, while the waterproof facestock maintains barcode readability through showers, swimming, and physical activity. Tamper-evident closure prevents transfer between individuals. Compatible with Zebra HC100, Datamax, and all major wristband printers.",
    keywords: "thermal wristband labels, hospital wristband rolls",
    sizes: ["25×254mm", "25×279mm", "Custom"],
    applications: ["Hospitals", "Events", "Theme parks"],
    features: [
      "Skin-safe, hypoallergenic adhesive tested for extended wear",
      "Waterproof — maintains barcode readability through water exposure",
      "Tamper-evident closure prevents transfer between individuals",
      "Compatible with Zebra HC100, Datamax, and all major wristband printers",
    ],
    moq: "10,000 labels",
    specifications: {
      "Facestock": "Waterproof synthetic",
      "Adhesive": "Skin-safe, hypoallergenic",
      "Closure": "Tamper-evident (no transfer)",
      "Water Resistance": "Yes (shower, swimming)",
      "Label Format": "Roll",
      "Min. Order Qty": "10,000 labels",
      "Lead Time": "10–15 Business Days",
      "Certification": "ISO 9001:2015",
    },
    tag: "New",
  },
  {
    slug: "fanfold-labels",
    name: "Fanfold Labels",
    subtitle: "Z-Fold Bulk Labels",
    heroDesc: "High-volume shipping operations need labels that load fast, feed reliably, and never run out at the wrong moment. Our Fanfold Labels are built for exactly that.",
    description: "Fanfold labels are the preferred format for high-throughput shipping and warehouse operations, eliminating the need to change rolls and enabling continuous printing from large stacks. Our Fanfold Labels are precision-folded to feed smoothly through all major label printers without jamming or misfeeding. Available in all standard shipping label sizes with perforations optimized for clean separation. Supplied on pallets for bulk warehouse operations.",
    keywords: "fanfold labels, 2-fold labels bulk",
    sizes: ["100×150mm", "4×6 inch", "Custom"],
    applications: ["High-volume shipping", "Warehouse operations", "E-commerce"],
    features: [
      "Precision-folded for smooth, jam-free feeding in all major printers",
      "Eliminates roll changes — continuous printing from large stacks",
      "Optimised perforations for clean, consistent label separation",
      "Bulk pallet supply available for high-volume warehouse operations",
    ],
    moq: "50,000 labels",
    specifications: {
      "Facestock": "Thermal-sensitive paper",
      "Adhesive": "Permanent acrylic",
      "Liner": "Glassine",
      "Label Format": "Fanfold (Z-fold)",
      "Perforation": "Optimised for clean separation",
      "Print Method": "Direct Thermal",
      "Min. Order Qty": "50,000 labels",
      "Lead Time": "10–15 Business Days",
      "Certification": "ISO 9001:2015",
    },
  },
  {
    slug: "custom-printed-labels",
    name: "Custom Printed Labels",
    subtitle: "Private Label Thermal",
    heroDesc: "Your brand deserves more than a blank white label. Our Custom Printed Labels combine professional design, premium materials, and full compliance — all under your name.",
    description: "Private label thermal labels give your business a professional edge and strengthen brand recognition at every touchpoint. Our Custom Printed Labels service covers everything from initial design consultation to finished, packaged product — with full-color printing, custom die-cutting, variable data, and serialization options. All materials are available in BPA-free, REACH-compliant, and food-contact-safe formulations. Minimum order from 50,000 labels with 15-day lead time.",
    keywords: "custom printed labels, private label thermal",
    sizes: ["55×25mm", "60×40mm", "75×50mm", "100×50mm", "100×150mm", "Custom"],
    applications: ["Brand labels", "Product identification", "Custom packaging"],
    features: [
      "Full-color printing with Pantone color matching available",
      "Custom die-cutting in any shape or size",
      "Variable data and serialization for product traceability",
      "BPA-free, REACH-compliant, and food-contact-safe options",
    ],
    moq: "50,000 labels",
    specifications: {
      "Facestock": "Paper / PP / PET (customer choice)",
      "Adhesive": "Permanent / Removable / Freezer (customer choice)",
      "Printing": "Full-color (Pantone matching available)",
      "Die-Cutting": "Any shape or size",
      "Variable Data": "Serialization, QR code, barcode",
      "Min. Order Qty": "50,000 labels",
      "Lead Time": "20–30 Business Days",
      "Certification": "ISO 9001:2015 / REACH / FDA",
    },
  },
];

export const INDUSTRIES = [
  {
    slug: "retail-pos",
    name: "Retail & POS",
    icon: "ShoppingCart",
    description: "Premium thermal receipt paper for retail chains, supermarkets, and restaurants. All products are BPA-free as standard (EU REACH Regulation EC 1907/2006), with phenol-free options available for retailers pursuing Blauer Engel (Blue Angel) eco-certification. Back-print option enables coupon, loyalty reward, and promotional printing on the reverse side of every receipt — turning each transaction into a marketing touchpoint. Compatible with Epson TM-series, Star TSP-series, Bixolon, and all major POS receipt printers. 80mm and 57mm widths; core sizes 12mm and 19mm.",
    keywords: "POS receipt paper supplier, thermal paper retail wholesale, 80mm POS paper rolls, receipt paper bulk order, 57mm thermal rolls, BPA free receipt paper EU, phenol free thermal paper, Blauer Engel thermal paper, back print receipt paper, Epson compatible thermal rolls",
    products: ["Standard POS Rolls", "Custom Printed Rolls", "Back Print Thermal Rolls"],
    priority: "P1",
  },
  {
    slug: "lottery-gaming",
    name: "Lottery & Gaming",
    icon: "Ticket",
    description: "Certified thermal paper for lottery terminals and gaming machines.",
    keywords: "lottery paper supplier, TITO thermal paper manufacturer",
    products: ["Lottery Gaming Rolls", "Casino TITO Rolls"],
    tag: "SEO",
  },
  {
    slug: "casino",
    name: "Casino",
    icon: "Coins",
    description: "High-performance TITO paper for casino slot machines and gaming terminals.",
    keywords: "Casino paper supplier, TITO thermal paper manufacturer",
    products: ["Casino TITO Rolls"],
    tag: "SEO",
  },
  {
    slug: "banking-finance",
    name: "Banking & Finance",
    icon: "Building2",
    description: "Archival-grade ATM & bank receipt rolls with 7-year image life, anti-static coating, and optional back-print for regulatory disclosures.",
    keywords: "ATM receipt paper supplier, bank thermal paper rolls, back print thermal paper, archival receipt paper",
    products: ["ATM & Bank Receipt Rolls", "Back Print Thermal Rolls"],
    tag: "SEO",
  },
  {
    slug: "healthcare-pharma",
    name: "Healthcare & Pharma",
    icon: "Heart",
    description: "Specialized thermal paper and labels engineered for the demanding requirements of hospitals, pharmacies, and clinical laboratories. All medical rolls are BPA-free certified and manufactured with a long-life archival coating preserving patient data for up to 10 years — meeting EU MDR and US FDA 21 CFR record-keeping requirements. Chemical-resistant surface withstands common hospital disinfectants (isopropyl alcohol, quaternary ammonium compounds). Wristband labels and specimen tube labels available in cryogenic grades (down to -80°C) for biobank and laboratory applications. Labeling symbols comply with ISO 15223-1:2021 medical device symbol standards.",
    keywords: "medical thermal paper BPA free, hospital receipt paper, pharmacy label manufacturer, FDA compliant thermal paper, EU MDR thermal paper, cryogenic labels -80C, specimen tube labels, patient wristband labels, ISO 15223 medical labels, archival thermal paper 10 year",
    products: ["Medical Rolls", "Wristband Labels", "Freezer Cold Chain Labels"],
    tag: "SEO",
  },
  {
    slug: "food-cold-chain",
    name: "Food & Cold Chain",
    icon: "Snowflake",
    description: "Certified thermal labels and paper for food processing, cold storage, and temperature-controlled logistics. Our Freezer Labels maintain adhesion and print legibility from -40°C to +70°C, passing freeze-thaw cycle testing for direct application to frozen product packaging. EU food contact compliant per Regulation (EC) No 1935/2004 — safe for direct contact with food surfaces. FSC-certified paper substrate available for sustainable packaging programs. Suitable for HACCP-compliant labeling in food processing facilities, supermarket deli counters, and pharmaceutical cold chain.",
    keywords: "freezer labels -40C, food contact thermal labels EU, cold chain labels manufacturer, HACCP labels food processing, EU food contact regulation 1935/2004, FSC certified food labels, temperature resistant labels, frozen food labels, cold storage barcode labels",
    products: ["Freezer Cold Chain Labels", "Direct Thermal Labels"],
    tag: "SEO",
  },
  {
    slug: "logistics-warehouse",
    name: "Logistics & Warehouse",
    icon: "Package",
    description: "High-volume direct thermal shipping labels and warehouse bin labels for 3PLs, fulfillment centers, and distribution hubs. Our labels are pre-tested on Zebra ZPL-series, Honeywell, and SATO printers, and meet GS1 logistic label standards (SSCC barcode) for automated sortation lines. Fanfold and roll formats available; permanent and removable adhesive options. Barcode legibility guaranteed for 24+ months under standard warehouse conditions.",
    keywords: "shipping labels bulk supplier, warehouse thermal labels, 4x6 shipping labels wholesale, fanfold labels manufacturer, Zebra compatible labels, 3PL thermal labels, GS1 SSCC barcode labels, Zebra ZPL labels Europe, warehouse bin labels bulk, DHL Hermes DPD compatible labels",
    products: ["Direct Thermal Labels", "Fanfold Labels", "Direct Thermal Rolls"],
  },
  {
    slug: "ecommerce",
    name: "E-Commerce & Fulfillment",
    icon: "ShoppingCart",
    description: "Purpose-built thermal shipping and product labels for Amazon FBA sellers, Shopify merchants, WooCommerce stores, and 3PL fulfillment centers. Our 4×6 inch (100×150mm) direct thermal shipping labels are pre-validated on Zebra GX430t, ZD420, and ZD621 — the printer models used at Amazon fulfillment centers — ensuring 100% scan-through-rate at Amazon's high-speed sortation conveyors. Barcode image life guaranteed 24 months, meeting Amazon FBA label retention requirements. GS1-128 and GS1 DataMatrix barcode formats supported for SSCC pallet labels and full GS1 compliance. FNSKU product labels (2×1 inch) available for Amazon product identification, printed at 300 DPI for reliable scanning at receiving docks. Fanfold format for automated print-and-apply lines; roll format for desktop Zebra, Dymo, and Rollo printers. Compatible with DHL, UPS, FedEx, USPS, and Amazon Logistics label formats for US domestic and international last-mile delivery. Permanent acrylic adhesive bonds reliably to cardboard, poly mailers, and bubble wrap — no label detachment during transit.",
    keywords: "ecommerce shipping labels wholesale, 4x6 thermal labels Amazon FBA, FNSKU labels bulk, Shopify shipping labels bulk, fulfillment center labels supplier, 3PL thermal labels, direct thermal labels e-commerce, Zebra GX430t labels, Amazon FBA label requirements, DHL shipping labels bulk, fanfold labels fulfillment, GS1-128 barcode labels, SSCC pallet labels, 100x150mm shipping labels",
    products: ["Direct Thermal Labels", "Fanfold Labels", "Custom Printed Rolls"],
    tag: "New",
  },
  {
    slug: "transportation",
    name: "Transportation",
    icon: "Bus",
    description: "Durable transit tickets and parking thermal paper for transport operators.",
    keywords: "parking ticket paper, transit thermal paper Europe",
    products: ["Transport Ticket Rolls", "Parking Ticketing Rolls"],
    tag: "New",
  },
  {
    slug: "automotive-industrial",
    name: "Automotive & Industrial",
    icon: "Wrench",
    description: "Industrial-grade thermal labels engineered to survive the harshest manufacturing environments. Our automotive labels comply with VDA 4902 (German Automotive Industry Association) goods tag standards, making them compatible with BMW, Volkswagen Group, Mercedes-Benz, and Tier-1 supplier logistics systems. Chemical-resistant facestock withstands engine oils, brake fluids, cutting fluids, and industrial solvents without smearing or delaminating. High-temperature variants rated to 150°C for under-hood and paint-shop applications. Available in synthetic (polyester/polyolefin) and paper facestocks; permanent and high-tack adhesive options. Barcode readability maintained after exposure to UV, abrasion, and chemical wash-down cycles.",
    keywords: "automotive thermal labels VDA 4902, industrial labels chemical resistant, BMW VW supplier labels, high temperature labels 150C, factory floor labels, parts tracking labels, synthetic thermal labels, polyester labels manufacturer, industrial barcode labels Europe",
    products: ["Chemical Resistant Labels", "High Temperature Labels", "Direct Thermal Labels"],
    tag: "New",
  },
  {
    slug: "events-hospitality",
    name: "Events & Hospitality",
    icon: "Calendar",
    description: "Event ticket paper and wristband labels for venues and hospitality.",
    keywords: "event ticket paper, wristbands supplier",
    products: ["Wristband Labels", "Custom Printed Rolls"],
    tag: "New",
  },
  {
    slug: "government-legal",
    name: "Government & Legal",
    icon: "Scale",
    description: "Archival-grade thermal paper for government receipts and legal documents.",
    keywords: "government receipt paper, archival thermal paper",
    products: ["Medical Rolls", "Standard POS Rolls"],
    tag: "New",
  },
  {
    slug: "cannabis-specialty",
    name: "Cannabis & Specialty",
    icon: "Leaf",
    description: "Compliance labels for cannabis dispensaries in USA and Canada.",
    keywords: "cannabis compliance labels USA Canada, dispensary thermal labels, state compliant cannabis labels, marijuana packaging labels wholesale",
    products: ["Tamper Evident Labels", "Custom Printed Labels"],
    tag: "New",
  },
];

export const GEO_REGIONS = [
  {
    slug: "eu",
    name: "Europe",
    flag: "🇪🇺",
    description: "BPA-free, REACH-compliant thermal paper rolls and labels for European distributors and importers. EU Commission Regulation (EU) 2024/3190 BPA ban compliant since January 2025.",
    keywords: "thermal paper supplier Europe, BPA free rolls EU, REACH compliant thermal paper, thermal labels EU wholesale",
    priority: "P1",
    compliance: ["BPA-Free (EU 2024/3190)", "REACH/RoHS", "ISO 9001:2015", "FSC Certified", "EU Food Contact"],
    shipping: "FOB Qingdao / Hamburg / Rotterdam — 18–25 days sea freight",
    countries: [
      {
        slug: "germany",
        name: "Germany",
        flag: "🇩🇪",
        lang: "DE",
        keywords: "Thermopapier Lieferant, Etiketten Hersteller Deutschland, Kassenrollen Großhandel, BPA-freies Thermopapier Deutschland",
        description: "Germany is Europe's largest thermal paper market, home to major distributors and POS equipment manufacturers. Koehler Paper, the global POS thermal paper leader, is headquartered in Germany — making German buyers highly knowledgeable about quality standards.",
        compliance: ["BPA-Free (EU 2024/3190)", "REACH Annex XVII", "ISO 9001:2015", "FSC Certified"],
        shipping: "FOB Qingdao → Hamburg (HH) — 18–22 days. DDP Germany available.",
        port: "Hamburg (HH)",
        leadTime: "18–22 days sea freight",
        highlights: [
          "Full German-language compliance documentation available",
          "BPA-free certified — meets EU 2024/3190 ban effective January 2025",
          "Compatible with Epson, Star, Bixolon, and all EU-market POS brands",
          "Competitive pricing vs. Koehler and local German distributors",
          "ISO 9001:2015 factory audit reports available on request",
        ],
        popularProducts: ["Standard POS Rolls 80×80mm", "Thermal Labels 100×150mm", "ATM Bank Receipt Rolls"],
      },
      {
        slug: "uk",
        name: "United Kingdom",
        flag: "🇬🇧",
        lang: "EN",
        keywords: "thermal paper supplier UK, thermal till rolls wholesale Britain, receipt paper rolls UK, thermal labels wholesale UK, till rolls bulk order",
        description: "The UK is one of Europe's most active thermal paper import markets, with strong demand from retail chains, hospitality, and logistics. Post-Brexit, UK buyers source independently from EU and Asian manufacturers. UK-specific sizes include 57×40mm and 80×80mm till rolls.",
        compliance: ["BPA-Free", "UK REACH", "ISO 9001:2015", "FSC Certified"],
        shipping: "FOB Qingdao → Felixstowe / Southampton — 25–30 days. DDP UK available.",
        port: "Felixstowe / Southampton",
        leadTime: "25–30 days sea freight",
        highlights: [
          "UK REACH compliant — independent post-Brexit compliance documentation",
          "BPA-free certified till rolls for UK retail and hospitality",
          "Standard UK sizes: 57×40mm, 80×80mm, 80×70mm",
          "DDP UK shipping available — no customs hassle for buyers",
          "English-language technical support and documentation",
        ],
        popularProducts: ["Standard POS Rolls (Till Rolls)", "Direct Thermal Labels 4×6", "ATM Bank Receipt Rolls"],
      },
      {
        slug: "france",
        name: "France",
        flag: "🇫🇷",
        lang: "FR",
        keywords: "fournisseur papier thermique France, étiquettes thermiques France, rouleaux caisse enregistreuse, papier thermique BPA gratuit France",
        description: "France has strict environmental regulations and was among the first EU countries to restrict BPA in thermal paper. French distributors require full REACH compliance documentation and prefer suppliers with FSC certification. Strong demand from retail, hospitality, and logistics sectors.",
        compliance: ["BPA-Free (EU 2024/3190)", "REACH Compliant", "ISO 9001:2015", "FSC Certified", "EU Food Contact"],
        shipping: "FOB Qingdao → Le Havre / Marseille — 20–25 days. DDP France available.",
        port: "Le Havre / Marseille",
        leadTime: "20–25 days sea freight",
        highlights: [
          "French-language compliance documentation available on request",
          "BPA-free certified — compliant with French environmental regulations",
          "FSC certified paper for eco-conscious French distributors",
          "EU food contact compliant for food-safe labeling applications",
          "Competitive pricing for pallet and container orders",
        ],
        popularProducts: ["Standard POS Rolls 80×80mm", "Thermal Labels", "Custom Printed Rolls"],
      },
      {
        slug: "netherlands",
        name: "Netherlands",
        flag: "🇳🇱",
        lang: "NL",
        keywords: "thermisch papier leverancier Nederland, thermische etiketten groothandel, kassarollen Nederland, BPA-vrij thermisch papier",
        description: "The Netherlands is a major European logistics hub, with Rotterdam being Europe's largest port. Dutch distributors often serve as regional re-distributors for the broader EU market. Strong demand from logistics, e-commerce, and retail sectors.",
        compliance: ["BPA-Free (EU 2024/3190)", "REACH/RoHS", "ISO 9001:2015", "FSC Certified"],
        shipping: "FOB Qingdao → Rotterdam (RTM) — 20–24 days. DDP Netherlands available.",
        port: "Rotterdam (RTM)",
        leadTime: "20–24 days sea freight",
        highlights: [
          "Rotterdam port delivery — Europe's largest logistics hub",
          "Ideal for EU re-distribution from Netherlands warehouse",
          "BPA-free and REACH compliant for Dutch and EU-wide distribution",
          "Shipping labels and logistics labels for Dutch e-commerce and 3PL",
          "Dutch-language documentation available on request",
        ],
        popularProducts: ["Direct Thermal Labels 100×150mm", "Standard POS Rolls", "Fanfold Labels"],
      },
      {
        slug: "poland",
        name: "Poland",
        flag: "🇵🇱",
        lang: "PL",
        keywords: "dostawca papieru termicznego Polska, etykiety termiczne hurtownia, rolki kasowe Polska, papier termiczny BPA-free Polska",
        description: "Poland is one of the fastest-growing thermal paper markets in Central Europe, driven by rapid retail expansion and a booming logistics sector. Polish buyers are price-sensitive and value reliable supply with EU compliance documentation.",
        compliance: ["BPA-Free (EU 2024/3190)", "REACH Compliant", "ISO 9001:2015", "FSC Certified"],
        shipping: "FOB Qingdao → Gdańsk / Hamburg → Poland — 22–28 days.",
        port: "Gdańsk / Hamburg",
        leadTime: "22–28 days sea freight",
        highlights: [
          "Competitive factory-direct pricing for price-sensitive Polish market",
          "BPA-free certified — EU 2024/3190 compliant",
          "Polish-language documentation available on request",
          "Strong logistics network via Gdańsk port and Hamburg",
          "Ideal for Polish distributors serving Central European markets",
        ],
        popularProducts: ["Standard POS Rolls", "Direct Thermal Labels", "Thermal Labels"],
      },
    ],
  },
  {
    slug: "us",
    name: "United States",
    flag: "🇺🇸",
    description: "FDA-compliant, Prop 65 compliant thermal paper rolls and labels for US distributors, importers, and e-commerce sellers. BPA-free, ISO 9001 certified, DDP shipping available.",
    keywords: "thermal paper supplier USA, thermal labels wholesale America, FDA compliant thermal paper, BPA free receipt paper USA, Prop 65 thermal paper",
    priority: "P1",
    compliance: ["FDA 21 CFR", "Prop 65 Compliant", "BPA-Free", "ISO 9001:2015", "FSC Certified"],
    shipping: "FOB Qingdao → Los Angeles (LA) / Long Beach (LB) — 14–18 days. DDP USA available.",
    highlights: [
      "FDA 21 CFR compliant for food contact applications",
      "Prop 65 compliant — no BPA, BPS, or BPAF",
      "DDP shipping to any US port — no customs hassle",
      "LTL and full container load (FCL) pricing available",
      "Cannabis labels compliant with state regulations (CA, CO, WA, OR, MI, IL, and more)",
      "Compatible with Zebra, Epson, Star, Bixolon, and all US-market printers",
    ],
    subpages: [
      { slug: "fda-compliant", name: "FDA Compliant", keywords: "FDA compliant thermal paper, BPA free thermal USA, 21 CFR thermal paper" },
      { slug: "cannabis-labels", name: "Cannabis Labels", keywords: "cannabis label supplier USA, dispensary thermal labels, state compliant cannabis labels" },
    ],
  },
  {
    slug: "ca",
    name: "Canada",
    flag: "🇨🇦",
    description: "Health Canada compliant, BPA-free thermal paper rolls and labels for Canadian distributors. Cannabis Act compliant labels for all provinces. Bilingual EN/FR documentation available.",
    keywords: "thermal paper supplier Canada, thermal labels wholesale Canada, BPA-free thermal paper Canada, Health Canada compliant, cannabis labels Canada",
    compliance: ["Health Canada Compliant", "BPA-Free", "ISO 9001:2015", "Cannabis Act Compliant", "CEPA Compliant"],
    shipping: "FOB Qingdao → Vancouver (Prince Rupert) — 10–15 days. FOB → Montreal — 22–26 days. DDP Canada available.",
    highlights: [
      "Health Canada compliant BPA-free thermal paper — full documentation provided",
      "Cannabis Act compliant labels for all provinces (ON, BC, AB, QC and more)",
      "Bilingual English/French documentation for Quebec and federal requirements",
      "CA/US standard sizes: 3⅛×230, 4×6 inch labels, 80×80mm POS rolls",
      "Vancouver port shipping — 10–15 days to BC; 18–22 days to Eastern Canada",
      "Custom OEM and private label for Canadian brands",
    ],
    subpages: [
      { slug: "cannabis-labels", name: "Cannabis Labels", keywords: "cannabis compliance labels Canada, Health Canada labels, Cannabis Act labels" },
    ],
  },
];

export const COMPLIANCE_ITEMS = [
  { slug: "bpa-free", name: "BPA-Free & Phenol-Free", icon: "ShieldCheck", color: "emerald", description: "BPA-free, BPS-free, bisphenol-free, and phenol-free routes are confirmed by product and quoted paper grade. Buyers should request the grade name, named chemical scope, and supporting declaration or test report before approval." },
  { slug: "reach-rohs", name: "REACH/RoHS", icon: "FileCheck", color: "blue", description: "REACH SVHC (Substances of Very High Concern) compliant thermal paper and labels. All products tested against the current SVHC candidate list (240+ substances). RoHS 2 (EU 2011/65/EU) compliant for label products. Full REACH declaration of conformity available." },
  { slug: "iso-9001", name: "ISO 9001:2015", icon: "Award", color: "orange", description: "ISO 9001:2015 certified manufacturing facility with documented quality management system covering raw material inspection, in-process quality control, and finished goods testing. Certificate issued by TÜV-recognized certification body. Annual surveillance audits conducted." },
  { slug: "fsc-paper", name: "FSC Certified", icon: "Leaf", color: "green", description: "FSC (Forest Stewardship Council) certified thermal paper from responsibly managed forests. Chain of custody certification maintained throughout the supply chain. Available for all paper-based products. Required by major European retail chains for sustainable packaging compliance." },
  { slug: "eu-food-contact", name: "EU Food Contact", icon: "UtensilsCrossed", color: "teal", description: "EU food contact compliant thermal paper and labels per Regulation (EC) No 1935/2004. Suitable for direct contact with food surfaces in deli, bakery, and food processing applications. Migration testing conducted per EN 1186 standard. Declaration of compliance available." },
  { slug: "fda-us", name: "FDA Compliant", icon: "Shield", color: "red", description: "FDA compliant thermal paper and labels for US food contact applications under 21 CFR. Suitable for food packaging, medical device labeling, and pharmaceutical applications in the US market. Full FDA compliance documentation available for import clearance." },
  { slug: "iso-15223", name: "ISO 15223 Medical", icon: "Award", color: "pink", description: "Medical device labeling symbols compliant with ISO 15223-1:2021 for healthcare and pharmaceutical applications. Wristband labels and specimen tube labels manufactured to medical device labeling standards. Required for CE-marked medical device packaging in the EU and MDR compliance." },
];

export const BLOG_POSTS = [
  {
    slug: "bpa-free-thermal-paper-europe",
    title: "BPA-Free Thermal Paper in Europe: Complete Compliance Guide 2025",
    excerpt: "Everything distributors need to know about BPA-free thermal paper regulations in the EU, REACH compliance, and sourcing from certified manufacturers.",
    category: "Compliance",
    readTime: "8 min",
    date: "2025-03-15",
    tag: "SEO",
  },
  {
    slug: "what-is-thermal-paper",
    title: "What Is Thermal Paper? A Complete Technical Guide",
    excerpt: "Understanding thermal paper chemistry, types, applications, and how to choose the right thermal paper for your business needs.",
    category: "Education",
    readTime: "12 min",
    date: "2025-02-28",
    tag: "SEO",
  },
  {
    slug: "lottery-ticket-paper-specifications",
    title: "Lottery Ticket Paper Specifications: What You Need to Know",
    excerpt: "Technical specifications for lottery terminal thermal paper including sensitivity, density, and compliance requirements for gaming operators.",
    category: "Products",
    readTime: "6 min",
    date: "2025-02-10",
    tag: "SEO",
  },
  {
    slug: "casino-receipt-paper-guide",
    title: "Casino TITO Paper Guide: Choosing the Right Thermal Paper",
    excerpt: "Complete guide to TITO (Ticket-In Ticket-Out) thermal paper for casino slot machines, including specifications and supplier selection.",
    category: "Products",
    readTime: "7 min",
    date: "2025-01-20",
    tag: "SEO",
  },
  {
    slug: "freezer-label-adhesive-guide",
    title: "Freezer Label Adhesive Types: Which One Do You Need?",
    excerpt: "Comparing cold chain label adhesives for freezer applications, from -20°C to -40°C, with performance data and application recommendations.",
    category: "Products",
    readTime: "9 min",
    date: "2025-01-05",
  },
  {
    slug: "reach-compliance-thermal-paper",
    title: "REACH Compliance for Thermal Paper: EU 2025 Update",
    excerpt: "Latest REACH SVHC regulations affecting thermal paper in Europe, what distributors must verify, and how to ensure compliant sourcing.",
    category: "Compliance",
    readTime: "10 min",
    date: "2024-12-18",
    tag: "SEO",
  },
  {
    slug: "direct-vs-thermal-transfer",
    title: "Direct Thermal vs Thermal Transfer: Which Label Is Right for You?",
    excerpt: "Side-by-side comparison of direct thermal and thermal transfer labels covering durability, cost, applications, and printer compatibility.",
    category: "Education",
    readTime: "8 min",
    date: "2024-11-15",
    tag: "SEO",
  },
  {
    slug: "cannabis-label-requirements-usa",
    title: "Cannabis Label Requirements by US State: 2025 Guide",
    excerpt: "State-by-state breakdown of cannabis label requirements in the USA, including thermal label specifications and compliance tips for dispensaries.",
    category: "Compliance",
    readTime: "15 min",
    date: "2024-12-01",
    tag: "New",
  },
  {
    slug: "how-to-print-logo-on-thermal-paper-rolls",
    title: "How to Print Your Logo on Thermal Paper Rolls: Complete Guide",
    excerpt: "Step-by-step guide to custom logo printing on thermal paper rolls, including back print options, coupon printing, QR codes, and MOQ requirements for B2B buyers.",
    category: "Education",
    readTime: "10 min",
    date: "2026-04-10",
    tag: "New",
  },
  {
    slug: "amazon-fba-thermal-labels-guide",
    title: "Amazon FBA Thermal Labels: Complete Compliance & Sourcing Guide 2026",
    excerpt: "Everything Amazon FBA sellers need to know about thermal shipping labels: 4x6 size requirements, GS1-128 barcode standards, Zebra printer compatibility, and bulk sourcing from China factories.",
    category: "E-Commerce",
    readTime: "12 min",
    date: "2026-04-08",
    tag: "New",
  },
  {
    slug: "thermal-paper-printer-compatibility-guide",
    title: "Thermal Paper Printer Compatibility Guide",
    excerpt: "Match receipt rolls to POS printers, payment terminals, ATMs, and kiosks using model, width, OD, core ID, winding, sensing, and sample checks.",
    category: "Education",
    readTime: "9 min",
    date: "2026-07-20",
    tag: "New",
  },
  {
    slug: "thermal-paper-roll-sizes-guide",
    title: "Thermal Paper Roll Sizes Guide",
    excerpt: "Measure width, outer diameter, length, core ID, GSM, and winding before ordering POS, payment terminal, ATM, kiosk, or receipt printer rolls.",
    category: "Education",
    readTime: "8 min",
    date: "2026-04-05",
    tag: "New",
  },
];

export const NAV_ITEMS = [
  { label: "Home", href: "/" },
  {
    label: "Products",
    href: "/products",
    children: [
      {
        label: "Thermal Paper Rolls",
        href: "/products/thermal-paper-rolls",
        children: THERMAL_PAPER_ROLLS.map((p) => ({
          label: p.name,
          href: `/products/thermal-paper-rolls/${p.slug}`,
          tag: p.priority === "P1" ? "P1" : p.tag,
        })),
      },
      {
        label: "Thermal Labels",
        href: "/products/thermal-labels",
        children: THERMAL_LABELS.map((l) => ({
          label: l.name,
          href: `/products/thermal-labels/${l.slug}`,
          tag: l.priority === "P1" ? "P1" : l.tag,
        })),
      },
      { label: "Private Label Printing", href: "/oem-custom/private-label", tag: "P1" },
      { label: "Request Free Samples →", href: "/samples" },
    ],
  },
  {
    label: "Industries",
    href: "/industries",
    children: INDUSTRIES.map((i) => ({ label: i.name, href: `/industries/${i.slug}`, tag: i.tag })),
  },
  {
    label: "Factory",
    href: "/factory",
    children: [
      { label: "Factory Overview",     href: "/factory/overview",      tag: "P1" },
      { label: "Equipment & Machines", href: "/factory/equipment" },
      { label: "Production Capacity",  href: "/factory/capacity" },
      { label: "Quality Control",      href: "/factory/quality-control" },
      { label: "Virtual Factory Tour", href: "/factory/virtual-tour" },
    ],
  },
  {
    label: "Compliance",
    href: "/compliance",
    children: [
      { label: "Certificates (download)", href: "/compliance/certificates",   tag: "P1" },
      { label: "BPA-free statement",      href: "/compliance/bpa-free",       tag: "SEO" },
      { label: "REACH & RoHS",            href: "/compliance/reach-rohs",     tag: "SEO" },
      { label: "ISO 9001",                href: "/compliance/iso-9001" },
      { label: "FSC® paper",              href: "/compliance/fsc-paper" },
      { label: "EU food contact",         href: "/compliance/eu-food-contact", tag: "New" },
      { label: "FDA compliant (US)",      href: "/compliance/fda-us",         tag: "New" },
    ],
  },
  {
    label: "Resources",
    href: "/blog",
    children: [
      { label: "Blog",         href: "/blog" },
      { label: "Case Studies", href: "/case-studies", tag: "New" },
      { label: "FAQ",          href: "/faq",          tag: "SEO" },
    ],
  },
  {
    label: "About",
    href: "/about",
    children: [
      { label: "About Us", href: "/about" },
      { label: "Contact",  href: "/contact", tag: "P1" },
    ],
  },
  {
    label: "Markets",
    href: "/eu",
    children: [
      { label: "🇪🇺 Europe (EU)",        href: "/eu",            tag: "GEO" },
      { label: "🇩🇪 Germany",            href: "/eu/germany" },
      { label: "🇬🇧 United Kingdom",     href: "/eu/uk" },
      { label: "🇫🇷 France",             href: "/eu/france" },
      { label: "🇳🇱 Netherlands",        href: "/eu/netherlands" },
      { label: "🇵🇱 Poland",             href: "/eu/poland" },
      { label: "🇺🇸 United States (US)", href: "/us",            tag: "GEO" },
      { label: "🇨🇦 Canada (CA)",        href: "/ca",            tag: "GEO" },
    ],
  },
];
